// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/baseuser.proto

package baseuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	common "proto/common"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   uint32                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Type                 string                `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	FirstName            string                `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string                `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserName             string                `protobuf:"bytes,7,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Gender               string                `protobuf:"bytes,8,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Languages            string                `protobuf:"bytes,9,opt,name=Languages,proto3" json:"Languages,omitempty"`
	Password             string                `protobuf:"bytes,10,opt,name=Password,proto3" json:"Password,omitempty"`
	PassWordConfirmed    string                `protobuf:"bytes,11,opt,name=PassWordConfirmed,proto3" json:"PassWordConfirmed,omitempty"`
	Age                  int32                 `protobuf:"varint,12,opt,name=Age,proto3" json:"Age,omitempty"`
	BirthDate            string                `protobuf:"bytes,13,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	PhoneNumber          string                `protobuf:"bytes,14,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Bio                  string                `protobuf:"bytes,15,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Headline             string                `protobuf:"bytes,16,opt,name=Headline,proto3" json:"Headline,omitempty"`
	Intent               string                `protobuf:"bytes,17,opt,name=Intent,proto3" json:"Intent,omitempty"`
	UserAddress          *common.Address       `protobuf:"bytes,18,opt,name=UserAddress,proto3" json:"UserAddress,omitempty"`
	UserEducation        *common.Education     `protobuf:"bytes,19,opt,name=UserEducation,proto3" json:"UserEducation,omitempty"`
	UserInterests        *common.Interests     `protobuf:"bytes,20,opt,name=UserInterests,proto3" json:"UserInterests,omitempty"`
	UserSubscriptions    *common.Subscriptions `protobuf:"bytes,21,opt,name=UserSubscriptions,proto3" json:"UserSubscriptions,omitempty"`
	Skills               *common.SkillSet      `protobuf:"bytes,22,opt,name=Skills,proto3" json:"Skills,omitempty"`
	Groups               []*common.TeamMember  `protobuf:"bytes,23,rep,name=Groups,proto3" json:"Groups,omitempty"`
	Teams                []*common.TeamMember  `protobuf:"bytes,24,rep,name=Teams,proto3" json:"Teams,omitempty"`
	SocialMedia          *common.SocialMedia   `protobuf:"bytes,25,opt,name=SocialMedia,proto3" json:"SocialMedia,omitempty"`
	Contact              *common.Contact       `protobuf:"bytes,26,opt,name=Contact,proto3" json:"Contact,omitempty"`
	Settings             *common.Settings      `protobuf:"bytes,27,opt,name=Settings,proto3" json:"Settings,omitempty"`
	Email                string                `protobuf:"bytes,28,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4213599b657b2d8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetLanguages() string {
	if m != nil {
		return m.Languages
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPassWordConfirmed() string {
	if m != nil {
		return m.PassWordConfirmed
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *User) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *User) GetUserAddress() *common.Address {
	if m != nil {
		return m.UserAddress
	}
	return nil
}

func (m *User) GetUserEducation() *common.Education {
	if m != nil {
		return m.UserEducation
	}
	return nil
}

func (m *User) GetUserInterests() *common.Interests {
	if m != nil {
		return m.UserInterests
	}
	return nil
}

func (m *User) GetUserSubscriptions() *common.Subscriptions {
	if m != nil {
		return m.UserSubscriptions
	}
	return nil
}

func (m *User) GetSkills() *common.SkillSet {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *User) GetGroups() []*common.TeamMember {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *User) GetTeams() []*common.TeamMember {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *User) GetSocialMedia() *common.SocialMedia {
	if m != nil {
		return m.SocialMedia
	}
	return nil
}

func (m *User) GetContact() *common.Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *User) GetSettings() *common.Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("proto/user/baseuser.proto", fileDescriptor_d4213599b657b2d8) }

var fileDescriptor_d4213599b657b2d8 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x51, 0x4f, 0xdb, 0x3e,
	0x14, 0xc5, 0x55, 0xa0, 0xa5, 0x75, 0x80, 0x3f, 0xf8, 0xcf, 0xd8, 0xa5, 0x43, 0x5a, 0x60, 0x9a,
	0x54, 0x4d, 0x53, 0x3a, 0xb1, 0x97, 0x3d, 0xec, 0xa5, 0xb4, 0x8c, 0x55, 0x02, 0x84, 0xdc, 0xa2,
	0x3d, 0xbb, 0xcd, 0x25, 0x58, 0x4b, 0xe2, 0xc8, 0x76, 0x34, 0xed, 0x8b, 0xee, 0xf3, 0x4c, 0x76,
	0x9c, 0xd0, 0xaa, 0x0f, 0x7b, 0xea, 0x3d, 0xe7, 0x77, 0xae, 0x4f, 0x9c, 0xa8, 0xe4, 0xb4, 0x50,
	0xd2, 0xc8, 0x61, 0xa9, 0x51, 0x0d, 0x17, 0x5c, 0xa3, 0x1d, 0x22, 0xe7, 0xf5, 0xdf, 0x26, 0x52,
	0x26, 0x29, 0x0e, 0x9d, 0x5a, 0x94, 0x4f, 0x43, 0x23, 0x32, 0xd4, 0x86, 0x67, 0x85, 0x0f, 0xf8,
	0xdd, 0xa5, 0xcc, 0x32, 0x99, 0xfb, 0x9f, 0x0a, 0x5d, 0xfc, 0xd9, 0x25, 0x3b, 0x8f, 0x1a, 0x15,
	0x3d, 0x20, 0x5b, 0xd3, 0x09, 0xb4, 0xc2, 0xd6, 0x60, 0x9f, 0x6d, 0x4d, 0x27, 0xf4, 0x0b, 0xe9,
	0x8d, 0x15, 0x72, 0x83, 0xf1, 0xc8, 0xc0, 0x56, 0xd8, 0x1a, 0x04, 0x97, 0xfd, 0xa8, 0x2a, 0x8a,
	0xea, 0xa2, 0x68, 0x5e, 0x17, 0xb1, 0x97, 0xb0, 0xdd, 0x7c, 0x2c, 0x62, 0xbf, 0xb9, 0xfd, 0xef,
	0xcd, 0x26, 0x4c, 0x29, 0xd9, 0x99, 0xff, 0x2e, 0x10, 0x76, 0xc2, 0xd6, 0xa0, 0xc7, 0xdc, 0x4c,
	0xcf, 0x48, 0xef, 0x9b, 0x50, 0xda, 0xdc, 0xf3, 0x0c, 0xa1, 0xed, 0xc0, 0x8b, 0x41, 0xfb, 0xa4,
	0x7b, 0xcb, 0x3d, 0xec, 0x38, 0xd8, 0x68, 0xcb, 0xec, 0xcd, 0x1c, 0xdb, 0xad, 0x58, 0xad, 0xe9,
	0x09, 0xe9, 0xdc, 0x60, 0x1e, 0xa3, 0x82, 0xae, 0x23, 0x5e, 0xd9, 0xb6, 0x5b, 0x9e, 0x27, 0x25,
	0x4f, 0x50, 0x43, 0xaf, 0x6a, 0x6b, 0x0c, 0x7b, 0xe2, 0x03, 0xd7, 0xfa, 0x97, 0x54, 0x31, 0x90,
	0xea, 0xc4, 0x5a, 0xd3, 0x8f, 0xe4, 0xc8, 0xce, 0x3f, 0xa4, 0x8a, 0xc7, 0x32, 0x7f, 0x12, 0x2a,
	0xc3, 0x18, 0x02, 0x17, 0xda, 0x04, 0xf4, 0x90, 0x6c, 0x8f, 0x12, 0x84, 0xbd, 0xb0, 0x35, 0x68,
	0x33, 0x3b, 0xda, 0xe6, 0x2b, 0xa1, 0xcc, 0xf3, 0x84, 0x1b, 0x84, 0xfd, 0xaa, 0xb9, 0x31, 0x68,
	0x48, 0x82, 0x87, 0x67, 0x99, 0xe3, 0x7d, 0x99, 0x2d, 0x50, 0xc1, 0x81, 0xe3, 0xab, 0x96, 0x3d,
	0xf1, 0x4a, 0x48, 0xf8, 0xcf, 0x11, 0x3b, 0xda, 0xa7, 0xfd, 0x8e, 0x3c, 0x4e, 0x45, 0x8e, 0x70,
	0x58, 0x3d, 0x6d, 0xad, 0xed, 0xfd, 0xa7, 0xb9, 0xc1, 0xdc, 0xc0, 0x51, 0x75, 0xff, 0x4a, 0xd1,
	0x0f, 0x24, 0xb0, 0xef, 0x68, 0x14, 0xc7, 0x0a, 0xb5, 0x06, 0xea, 0xbe, 0x5e, 0x37, 0xf2, 0x9a,
	0xad, 0x42, 0xfa, 0x89, 0xec, 0x5b, 0x79, 0x1d, 0x97, 0x4b, 0x6e, 0x84, 0xcc, 0xe1, 0x7f, 0x97,
	0x26, 0x51, 0xe3, 0xb0, 0xf5, 0x40, 0xbd, 0x61, 0xbb, 0x14, 0x6a, 0xa3, 0xe1, 0xd8, 0x6f, 0x34,
	0x0e, 0x5b, 0x0f, 0xd0, 0xaf, 0xe4, 0xc8, 0x1a, 0xb3, 0x72, 0xa1, 0x97, 0x4a, 0x14, 0xf6, 0x14,
	0x0d, 0xaf, 0xdc, 0xd6, 0x41, 0xb4, 0xe6, 0xb2, 0xcd, 0x20, 0x3d, 0x27, 0x9d, 0xd9, 0x4f, 0x91,
	0xa6, 0x1a, 0x4e, 0xdc, 0x4a, 0x2f, 0x72, 0x72, 0x86, 0x86, 0x79, 0x40, 0xdf, 0x91, 0xce, 0x8d,
	0x92, 0x65, 0xa1, 0xe1, 0x75, 0xb8, 0x3d, 0x08, 0x2e, 0x83, 0x68, 0x8e, 0x3c, 0xbb, 0x43, 0xfb,
	0x4e, 0x99, 0x47, 0xf4, 0x9c, 0xb4, 0xad, 0xab, 0x01, 0x36, 0x33, 0x15, 0xa1, 0x11, 0x09, 0x66,
	0x72, 0x29, 0x78, 0x7a, 0x87, 0xb1, 0xe0, 0x70, 0xea, 0xfa, 0xf6, 0xa2, 0x15, 0x8f, 0xad, 0x06,
	0xe8, 0x05, 0xd9, 0x1d, 0xcb, 0xdc, 0xf0, 0xa5, 0x81, 0xbe, 0x7f, 0xc9, 0x5e, 0xb3, 0x1a, 0xd0,
	0xf7, 0xa4, 0x3b, 0x43, 0x63, 0x44, 0x9e, 0x68, 0x78, 0x53, 0x5f, 0xc0, 0x1b, 0xac, 0x41, 0xf4,
	0x98, 0xb4, 0xaf, 0x33, 0x2e, 0x52, 0x38, 0x73, 0x9f, 0xb2, 0x12, 0x8b, 0x8e, 0xfb, 0xab, 0x7d,
	0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xb7, 0x6d, 0x65, 0x38, 0x04, 0x00, 0x00,
}
