// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/investor-user/investoruser.proto

package investoruser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	common "proto/common"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvestorUser struct {
	UserID               uint32               `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Experience           []*common.Experience `protobuf:"bytes,5,rep,name=Experience,proto3" json:"Experience,omitempty"`
	Investment           []*common.Investment `protobuf:"bytes,6,rep,name=Investment,proto3" json:"Investment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InvestorUser) Reset()         { *m = InvestorUser{} }
func (m *InvestorUser) String() string { return proto.CompactTextString(m) }
func (*InvestorUser) ProtoMessage()    {}
func (*InvestorUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d26bf71e7b09bea6, []int{0}
}

func (m *InvestorUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvestorUser.Unmarshal(m, b)
}
func (m *InvestorUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvestorUser.Marshal(b, m, deterministic)
}
func (m *InvestorUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvestorUser.Merge(m, src)
}
func (m *InvestorUser) XXX_Size() int {
	return xxx_messageInfo_InvestorUser.Size(m)
}
func (m *InvestorUser) XXX_DiscardUnknown() {
	xxx_messageInfo_InvestorUser.DiscardUnknown(m)
}

var xxx_messageInfo_InvestorUser proto.InternalMessageInfo

func (m *InvestorUser) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *InvestorUser) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *InvestorUser) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *InvestorUser) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *InvestorUser) GetExperience() []*common.Experience {
	if m != nil {
		return m.Experience
	}
	return nil
}

func (m *InvestorUser) GetInvestment() []*common.Investment {
	if m != nil {
		return m.Investment
	}
	return nil
}

func init() {
	proto.RegisterType((*InvestorUser)(nil), "InvestorUser")
}

func init() {
	proto.RegisterFile("proto/investor-user/investoruser.proto", fileDescriptor_d26bf71e7b09bea6)
}

var fileDescriptor_d26bf71e7b09bea6 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcc, 0x2b, 0x4b, 0x2d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2d, 0x2d, 0x4e, 0x2d, 0x82,
	0xf3, 0x40, 0x1c, 0x3d, 0xb0, 0x02, 0x29, 0xf9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0x30,
	0x2f, 0xa9, 0x34, 0x4d, 0xbf, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x00, 0xaa, 0x40,
	0x12, 0x62, 0x50, 0x72, 0x7e, 0x6e, 0x6e, 0x7e, 0x1e, 0x94, 0x82, 0x48, 0x29, 0x75, 0x31, 0x71,
	0xf1, 0x78, 0x42, 0x8d, 0x0c, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe3, 0x62, 0x03, 0xd1, 0x9e, 0x2e,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x50, 0x9e, 0x90, 0x05, 0x17, 0xa7, 0x73, 0x51, 0x6a,
	0x62, 0x49, 0x6a, 0x8a, 0x63, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x94, 0x1e, 0xc4,
	0x62, 0x3d, 0x98, 0xc5, 0x7a, 0x21, 0x30, 0x8b, 0x83, 0x10, 0x8a, 0x41, 0x3a, 0x43, 0x0b, 0x52,
	0xa0, 0x3a, 0x99, 0x09, 0xeb, 0x84, 0x2b, 0x16, 0x12, 0xe1, 0x62, 0x0d, 0xc9, 0x2c, 0xc9, 0x49,
	0x95, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xb4, 0xb9, 0xb8, 0x5c, 0x2b, 0x0a,
	0x52, 0x8b, 0x32, 0x53, 0xf3, 0x92, 0x53, 0x25, 0x58, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xb8, 0xf5,
	0x10, 0x42, 0x41, 0x48, 0xd2, 0x20, 0xc5, 0x10, 0xef, 0xe5, 0xa6, 0xe6, 0x95, 0x48, 0xb0, 0x41,
	0x15, 0x23, 0x84, 0x82, 0x90, 0xa4, 0x93, 0xd8, 0xc0, 0xce, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x95, 0xdb, 0x2e, 0x79, 0x01, 0x00, 0x00,
}
