// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package usersService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	group "proto/group"
	investor_user "proto/investor-user"
	startup_user "proto/startup-user"
	team "proto/team"
	user "proto/user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUsersSearchRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	MaxResults           int32    `protobuf:"varint,2,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersSearchRequest) Reset()         { *m = GetUsersSearchRequest{} }
func (m *GetUsersSearchRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersSearchRequest) ProtoMessage()    {}
func (*GetUsersSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *GetUsersSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersSearchRequest.Unmarshal(m, b)
}
func (m *GetUsersSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersSearchRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersSearchRequest.Merge(m, src)
}
func (m *GetUsersSearchRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersSearchRequest.Size(m)
}
func (m *GetUsersSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersSearchRequest proto.InternalMessageInfo

func (m *GetUsersSearchRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUsersSearchRequest) GetMaxResults() int32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

type Uint32TypeRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uint32TypeRequest) Reset()         { *m = Uint32TypeRequest{} }
func (m *Uint32TypeRequest) String() string { return proto.CompactTextString(m) }
func (*Uint32TypeRequest) ProtoMessage()    {}
func (*Uint32TypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Uint32TypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint32TypeRequest.Unmarshal(m, b)
}
func (m *Uint32TypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint32TypeRequest.Marshal(b, m, deterministic)
}
func (m *Uint32TypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint32TypeRequest.Merge(m, src)
}
func (m *Uint32TypeRequest) XXX_Size() int {
	return xxx_messageInfo_Uint32TypeRequest.Size(m)
}
func (m *Uint32TypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint32TypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Uint32TypeRequest proto.InternalMessageInfo

func (m *Uint32TypeRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StringTypeRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringTypeRequest) Reset()         { *m = StringTypeRequest{} }
func (m *StringTypeRequest) String() string { return proto.CompactTextString(m) }
func (*StringTypeRequest) ProtoMessage()    {}
func (*StringTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *StringTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringTypeRequest.Unmarshal(m, b)
}
func (m *StringTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringTypeRequest.Marshal(b, m, deterministic)
}
func (m *StringTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringTypeRequest.Merge(m, src)
}
func (m *StringTypeRequest) XXX_Size() int {
	return xxx_messageInfo_StringTypeRequest.Size(m)
}
func (m *StringTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StringTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StringTypeRequest proto.InternalMessageInfo

func (m *StringTypeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserResponse struct {
	Users                []*user.User `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsers() []*user.User {
	if m != nil {
		return m.Users
	}
	return nil
}

type StartupUserResponse struct {
	Users                []*startup_user.StartupUser `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StartupUserResponse) Reset()         { *m = StartupUserResponse{} }
func (m *StartupUserResponse) String() string { return proto.CompactTextString(m) }
func (*StartupUserResponse) ProtoMessage()    {}
func (*StartupUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *StartupUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupUserResponse.Unmarshal(m, b)
}
func (m *StartupUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupUserResponse.Marshal(b, m, deterministic)
}
func (m *StartupUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupUserResponse.Merge(m, src)
}
func (m *StartupUserResponse) XXX_Size() int {
	return xxx_messageInfo_StartupUserResponse.Size(m)
}
func (m *StartupUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartupUserResponse proto.InternalMessageInfo

func (m *StartupUserResponse) GetUsers() []*startup_user.StartupUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type InvestorUserResponse struct {
	Users                []*investor_user.InvestorUser `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *InvestorUserResponse) Reset()         { *m = InvestorUserResponse{} }
func (m *InvestorUserResponse) String() string { return proto.CompactTextString(m) }
func (*InvestorUserResponse) ProtoMessage()    {}
func (*InvestorUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{5}
}

func (m *InvestorUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvestorUserResponse.Unmarshal(m, b)
}
func (m *InvestorUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvestorUserResponse.Marshal(b, m, deterministic)
}
func (m *InvestorUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvestorUserResponse.Merge(m, src)
}
func (m *InvestorUserResponse) XXX_Size() int {
	return xxx_messageInfo_InvestorUserResponse.Size(m)
}
func (m *InvestorUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvestorUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvestorUserResponse proto.InternalMessageInfo

func (m *InvestorUserResponse) GetUsers() []*investor_user.InvestorUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type TeamResponse struct {
	Teams                []*team.Team `protobuf:"bytes,1,rep,name=Teams,proto3" json:"Teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TeamResponse) Reset()         { *m = TeamResponse{} }
func (m *TeamResponse) String() string { return proto.CompactTextString(m) }
func (*TeamResponse) ProtoMessage()    {}
func (*TeamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{6}
}

func (m *TeamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamResponse.Unmarshal(m, b)
}
func (m *TeamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamResponse.Marshal(b, m, deterministic)
}
func (m *TeamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamResponse.Merge(m, src)
}
func (m *TeamResponse) XXX_Size() int {
	return xxx_messageInfo_TeamResponse.Size(m)
}
func (m *TeamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamResponse proto.InternalMessageInfo

func (m *TeamResponse) GetTeams() []*team.Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type GroupResponse struct {
	Groups               []*group.Group `protobuf:"bytes,1,rep,name=Groups,proto3" json:"Groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupResponse) Reset()         { *m = GroupResponse{} }
func (m *GroupResponse) String() string { return proto.CompactTextString(m) }
func (*GroupResponse) ProtoMessage()    {}
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{7}
}

func (m *GroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupResponse.Unmarshal(m, b)
}
func (m *GroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupResponse.Marshal(b, m, deterministic)
}
func (m *GroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupResponse.Merge(m, src)
}
func (m *GroupResponse) XXX_Size() int {
	return xxx_messageInfo_GroupResponse.Size(m)
}
func (m *GroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupResponse proto.InternalMessageInfo

func (m *GroupResponse) GetGroups() []*group.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type UpdateOrCreateEntityResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrCreateEntityResponse) Reset()         { *m = UpdateOrCreateEntityResponse{} }
func (m *UpdateOrCreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrCreateEntityResponse) ProtoMessage()    {}
func (*UpdateOrCreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{8}
}

func (m *UpdateOrCreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrCreateEntityResponse.Unmarshal(m, b)
}
func (m *UpdateOrCreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrCreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOrCreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrCreateEntityResponse.Merge(m, src)
}
func (m *UpdateOrCreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrCreateEntityResponse.Size(m)
}
func (m *UpdateOrCreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrCreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrCreateEntityResponse proto.InternalMessageInfo

func (m *UpdateOrCreateEntityResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func init() {
	proto.RegisterType((*GetUsersSearchRequest)(nil), "usersService.GetUsersSearchRequest")
	proto.RegisterType((*Uint32TypeRequest)(nil), "usersService.Uint32TypeRequest")
	proto.RegisterType((*StringTypeRequest)(nil), "usersService.StringTypeRequest")
	proto.RegisterType((*UserResponse)(nil), "usersService.UserResponse")
	proto.RegisterType((*StartupUserResponse)(nil), "usersService.StartupUserResponse")
	proto.RegisterType((*InvestorUserResponse)(nil), "usersService.InvestorUserResponse")
	proto.RegisterType((*TeamResponse)(nil), "usersService.TeamResponse")
	proto.RegisterType((*GroupResponse)(nil), "usersService.GroupResponse")
	proto.RegisterType((*UpdateOrCreateEntityResponse)(nil), "usersService.UpdateOrCreateEntityResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x7f, 0x4f, 0x13, 0x41,
	0x10, 0x4d, 0x31, 0xa0, 0x4e, 0x5b, 0x4c, 0x17, 0x8d, 0xb5, 0x18, 0xc4, 0xc3, 0x18, 0x22, 0xe1,
	0x48, 0x20, 0x46, 0x8d, 0x89, 0x04, 0x84, 0x34, 0x35, 0x96, 0x1f, 0x57, 0x48, 0x94, 0xf8, 0x87,
	0x47, 0x3b, 0xe0, 0x25, 0xed, 0xb5, 0xde, 0xee, 0x11, 0xfb, 0x91, 0xfc, 0x96, 0xe6, 0x76, 0xf6,
	0x8e, 0xdd, 0x16, 0xcb, 0x5d, 0xb9, 0x7f, 0x9a, 0xee, 0xcc, 0xbc, 0xb7, 0xb3, 0x6f, 0x67, 0x66,
	0x0f, 0x16, 0x06, 0x41, 0x5f, 0xf4, 0x37, 0x38, 0x06, 0x57, 0x5e, 0x1b, 0x6d, 0xb9, 0x62, 0xa5,
	0x90, 0x63, 0xc0, 0x5b, 0x64, 0xab, 0x3d, 0xa3, 0x90, 0xc8, 0xb6, 0x71, 0xee, 0x72, 0x8c, 0xfe,
	0x50, 0x60, 0xec, 0x12, 0xe8, 0xf6, 0xa4, 0x2b, 0xfa, 0xa3, 0x5c, 0x4f, 0xc9, 0x75, 0x19, 0xf4,
	0xc3, 0x01, 0xfd, 0x2a, 0xc7, 0x2b, 0xb5, 0xa3, 0x70, 0x03, 0x11, 0x0e, 0xd6, 0x25, 0xad, 0x5a,
	0x68, 0xcc, 0xaf, 0x29, 0xca, 0xf3, 0xaf, 0x90, 0x8b, 0x7e, 0x40, 0x61, 0xf1, 0xea, 0x3a, 0xce,
	0x3a, 0x86, 0x27, 0x75, 0x14, 0xa7, 0x94, 0xaf, 0x1b, 0xb4, 0x7f, 0x39, 0xf8, 0x3b, 0x44, 0x2e,
	0x58, 0x15, 0xee, 0x37, 0x91, 0x73, 0xf7, 0x12, 0xab, 0x85, 0xe5, 0xc2, 0xea, 0x43, 0x27, 0x5e,
	0xb2, 0x25, 0x80, 0xa6, 0xfb, 0xc7, 0x41, 0x1e, 0x76, 0x05, 0xaf, 0xce, 0x2c, 0x17, 0x56, 0x67,
	0x1d, 0xcd, 0x62, 0xad, 0x40, 0xe5, 0xd4, 0xf3, 0xc5, 0xd6, 0xe6, 0xc9, 0x70, 0x80, 0x31, 0xdd,
	0x3c, 0xcc, 0x34, 0x3a, 0x92, 0xa9, 0xec, 0xcc, 0x34, 0x3a, 0xd6, 0x3a, 0x54, 0x5a, 0x22, 0xf0,
	0xfc, 0x4b, 0x3d, 0xe8, 0xbf, 0x7b, 0x5a, 0x6b, 0x50, 0x8a, 0x72, 0x74, 0x90, 0x0f, 0xfa, 0x3e,
	0x47, 0xb6, 0x08, 0xb3, 0x32, 0xe7, 0x6a, 0x61, 0xf9, 0xde, 0x6a, 0x71, 0x73, 0xd6, 0x96, 0x5e,
	0xb2, 0x59, 0x1f, 0x60, 0xa1, 0x45, 0x82, 0x18, 0x18, 0xcb, 0xc4, 0x94, 0x6c, 0x3d, 0x48, 0x41,
	0x3f, 0xc2, 0xe3, 0x86, 0x12, 0xc9, 0xc0, 0xae, 0x98, 0xd8, 0xb2, 0x6d, 0x44, 0x29, 0xf0, 0x1a,
	0x94, 0x4e, 0xd0, 0xed, 0xe9, 0x49, 0x46, 0xeb, 0xeb, 0x24, 0xa5, 0x97, 0x6c, 0xd6, 0x06, 0x94,
	0xeb, 0xd1, 0xad, 0x26, 0xd1, 0x4b, 0x30, 0x27, 0x0d, 0x71, 0xf8, 0x9c, 0x4d, 0x7e, 0x65, 0xb5,
	0x3e, 0xc1, 0xf3, 0xd3, 0x41, 0xc7, 0x15, 0x78, 0x18, 0x7c, 0x0e, 0xd0, 0x15, 0xb8, 0xef, 0x0b,
	0x4f, 0x0c, 0x35, 0x3c, 0xb4, 0xc2, 0x76, 0x1b, 0x39, 0xbf, 0x08, 0xbb, 0x52, 0xbf, 0x07, 0x8e,
	0x66, 0xd9, 0xfc, 0xcb, 0x48, 0xc3, 0xb8, 0x2e, 0xd9, 0x17, 0x28, 0xaa, 0xab, 0xdf, 0x1d, 0x36,
	0xf6, 0xd8, 0x0b, 0x5b, 0xaf, 0x5a, 0x7b, 0xec, 0x0a, 0x6b, 0xb5, 0x91, 0x00, 0x5d, 0x9f, 0x23,
	0xa8, 0x24, 0x5c, 0xd1, 0xaf, 0xef, 0xf6, 0x70, 0x94, 0x71, 0xec, 0xbe, 0x27, 0x32, 0x36, 0x61,
	0x3e, 0x61, 0xdc, 0xef, 0xb9, 0x5e, 0xf7, 0x6e, 0x74, 0xc7, 0x09, 0x1d, 0xdf, 0x1d, 0x46, 0x20,
	0xb6, 0x62, 0x46, 0xdf, 0xd8, 0x05, 0x13, 0x29, 0xbf, 0x01, 0xab, 0xa3, 0xd0, 0x8a, 0x28, 0x9d,
	0x8c, 0x2f, 0x47, 0x8f, 0x31, 0x5e, 0xa9, 0x67, 0xb0, 0x50, 0x47, 0xa1, 0x97, 0x58, 0x3a, 0x6a,
	0xcb, 0x0c, 0xb8, 0xb1, 0x92, 0xb7, 0x01, 0xa8, 0x7c, 0x22, 0x2b, 0xa3, 0xc6, 0xa9, 0xbd, 0x19,
	0x61, 0x9e, 0x54, 0x67, 0x4d, 0xa8, 0x90, 0x5d, 0xcb, 0x9c, 0x19, 0xcd, 0x94, 0x89, 0xee, 0x10,
	0x18, 0xd9, 0xf5, 0x6c, 0x99, 0xd9, 0x60, 0x99, 0x08, 0xb7, 0x01, 0xc8, 0x7f, 0x87, 0x03, 0x92,
	0x3f, 0xb7, 0x03, 0x92, 0x3f, 0xaf, 0x03, 0x7e, 0x07, 0xd8, 0xc3, 0x2e, 0xaa, 0x03, 0xde, 0x5a,
	0x14, 0x59, 0xa8, 0x7f, 0x42, 0x85, 0xa8, 0xf5, 0xa3, 0xe7, 0xba, 0x83, 0x0b, 0x8c, 0x76, 0x30,
	0xd4, 0xc8, 0x75, 0x8b, 0x1f, 0x50, 0xa6, 0x2d, 0x8e, 0x82, 0xfe, 0x85, 0xd7, 0xc5, 0x7c, 0xd9,
	0x93, 0xfe, 0x89, 0xc6, 0x38, 0xa3, 0x99, 0x3e, 0x5d, 0x7d, 0x4e, 0x4b, 0x90, 0xdc, 0xbf, 0x24,
	0xc8, 0xf5, 0x70, 0x6f, 0xe5, 0x93, 0x10, 0xf1, 0xee, 0x0e, 0x1b, 0x9d, 0xdb, 0xb9, 0x29, 0x7b,
	0xf6, 0x0e, 0xca, 0x09, 0xec, 0x20, 0xd5, 0xe4, 0x57, 0xc0, 0xf7, 0x72, 0x2a, 0x13, 0x30, 0xe5,
	0x90, 0x1f, 0x43, 0xc6, 0xf3, 0x3c, 0x2d, 0xf2, 0x58, 0x8e, 0x6d, 0x85, 0x6c, 0xf8, 0x9d, 0x90,
	0x8b, 0x60, 0x98, 0xf9, 0x71, 0x31, 0x1e, 0xfa, 0x1d, 0x28, 0x92, 0x9c, 0xf2, 0xa9, 0x66, 0xea,
	0xe5, 0xce, 0xa4, 0xfc, 0x57, 0x28, 0xd5, 0x51, 0x48, 0x5c, 0x3a, 0xe9, 0x17, 0x47, 0x9e, 0x2f,
	0xe3, 0x5b, 0xe2, 0x40, 0xaa, 0xa3, 0xd8, 0x6e, 0xba, 0x91, 0x8c, 0x7c, 0x87, 0xf0, 0x28, 0xe6,
	0x4b, 0x2d, 0xf7, 0x44, 0xc2, 0x1d, 0x28, 0x92, 0x1c, 0xd3, 0x2b, 0x76, 0x06, 0x45, 0x6a, 0x03,
	0xa2, 0xc8, 0xb3, 0x0f, 0xce, 0xe7, 0xe4, 0xc7, 0xf1, 0xd6, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x77, 0xda, 0xbe, 0xb8, 0xde, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	// Define Get, Update, Create, Delete requests for all user types
	GetUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByUsername(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByEmail(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUsersByType(ctx context.Context, in *GetUsersSearchRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetStartupUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*StartupUserResponse, error)
	GetInvestorUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*InvestorUserResponse, error)
	CreateUser(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	CreateStartupUser(ctx context.Context, in *startup_user.StartupUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	CreateInvestorUser(ctx context.Context, in *investor_user.InvestorUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	UpdateUser(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	UpdateStartupUser(ctx context.Context, in *startup_user.StartupUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	UpdateInvestorUser(ctx context.Context, in *investor_user.InvestorUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteStartupUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteInvestorUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteProfile(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	// Define Get, Update, Create, Delete requests for all team types
	CreateTeam(ctx context.Context, in *team.Team, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	UpdateTeam(ctx context.Context, in *team.Team, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteTeam(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	GetTeamById(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*team.Team, error)
	GetTeamByName(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error)
	GetTeamByEmail(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error)
	GetTeamsByType(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error)
	GetTeamsByIndustry(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*TeamResponse, error)
	// Define Get, Update, Create, Delete requests for all group types
	CreateGroup(ctx context.Context, in *group.Group, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	GetGroupById(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	GetGroupByName(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	GetGroupsByType(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	UpdateGroup(ctx context.Context, in *group.Group, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
	DeleteGroup(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserByUsername(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserByEmail(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetUserByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUsersByType(ctx context.Context, in *GetUsersSearchRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetUsersByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetStartupUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*StartupUserResponse, error) {
	out := new(StartupUserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetStartupUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetInvestorUserByID(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*InvestorUserResponse, error) {
	out := new(InvestorUserResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetInvestorUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateStartupUser(ctx context.Context, in *startup_user.StartupUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/CreateStartupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateInvestorUser(ctx context.Context, in *investor_user.InvestorUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/CreateInvestorUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateStartupUser(ctx context.Context, in *startup_user.StartupUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/UpdateStartupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateInvestorUser(ctx context.Context, in *investor_user.InvestorUser, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/UpdateInvestorUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteStartupUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteStartupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteInvestorUser(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteInvestorUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteProfile(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateTeam(ctx context.Context, in *team.Team, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateTeam(ctx context.Context, in *team.Team, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/UpdateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteTeam(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetTeamById(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*team.Team, error) {
	out := new(team.Team)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetTeamById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetTeamByName(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error) {
	out := new(team.Team)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetTeamByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetTeamByEmail(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error) {
	out := new(team.Team)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetTeamByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetTeamsByType(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*team.Team, error) {
	out := new(team.Team)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetTeamsByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetTeamsByIndustry(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*TeamResponse, error) {
	out := new(TeamResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetTeamsByIndustry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateGroup(ctx context.Context, in *group.Group, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetGroupById(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetGroupById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetGroupByName(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetGroupByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetGroupsByType(ctx context.Context, in *StringTypeRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/GetGroupsByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateGroup(ctx context.Context, in *group.Group, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteGroup(ctx context.Context, in *Uint32TypeRequest, opts ...grpc.CallOption) (*UpdateOrCreateEntityResponse, error) {
	out := new(UpdateOrCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/usersService.UsersService/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	// Define Get, Update, Create, Delete requests for all user types
	GetUserByID(context.Context, *Uint32TypeRequest) (*UserResponse, error)
	GetUserByUsername(context.Context, *StringTypeRequest) (*UserResponse, error)
	GetUserByEmail(context.Context, *StringTypeRequest) (*UserResponse, error)
	GetUsersByType(context.Context, *GetUsersSearchRequest) (*UserResponse, error)
	GetStartupUserByID(context.Context, *Uint32TypeRequest) (*StartupUserResponse, error)
	GetInvestorUserByID(context.Context, *Uint32TypeRequest) (*InvestorUserResponse, error)
	CreateUser(context.Context, *user.User) (*UpdateOrCreateEntityResponse, error)
	CreateStartupUser(context.Context, *startup_user.StartupUser) (*UpdateOrCreateEntityResponse, error)
	CreateInvestorUser(context.Context, *investor_user.InvestorUser) (*UpdateOrCreateEntityResponse, error)
	UpdateUser(context.Context, *user.User) (*UpdateOrCreateEntityResponse, error)
	UpdateStartupUser(context.Context, *startup_user.StartupUser) (*UpdateOrCreateEntityResponse, error)
	UpdateInvestorUser(context.Context, *investor_user.InvestorUser) (*UpdateOrCreateEntityResponse, error)
	DeleteUser(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
	DeleteStartupUser(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
	DeleteInvestorUser(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
	DeleteProfile(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
	// Define Get, Update, Create, Delete requests for all team types
	CreateTeam(context.Context, *team.Team) (*UpdateOrCreateEntityResponse, error)
	UpdateTeam(context.Context, *team.Team) (*UpdateOrCreateEntityResponse, error)
	DeleteTeam(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
	GetTeamById(context.Context, *Uint32TypeRequest) (*team.Team, error)
	GetTeamByName(context.Context, *StringTypeRequest) (*team.Team, error)
	GetTeamByEmail(context.Context, *StringTypeRequest) (*team.Team, error)
	GetTeamsByType(context.Context, *StringTypeRequest) (*team.Team, error)
	GetTeamsByIndustry(context.Context, *StringTypeRequest) (*TeamResponse, error)
	// Define Get, Update, Create, Delete requests for all group types
	CreateGroup(context.Context, *group.Group) (*UpdateOrCreateEntityResponse, error)
	GetGroupById(context.Context, *Uint32TypeRequest) (*GroupResponse, error)
	GetGroupByName(context.Context, *Uint32TypeRequest) (*GroupResponse, error)
	GetGroupsByType(context.Context, *StringTypeRequest) (*GroupResponse, error)
	UpdateGroup(context.Context, *group.Group) (*UpdateOrCreateEntityResponse, error)
	DeleteGroup(context.Context, *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) GetUserByID(ctx context.Context, req *Uint32TypeRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (*UnimplementedUsersServiceServer) GetUserByUsername(ctx context.Context, req *StringTypeRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUsername not implemented")
}
func (*UnimplementedUsersServiceServer) GetUserByEmail(ctx context.Context, req *StringTypeRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (*UnimplementedUsersServiceServer) GetUsersByType(ctx context.Context, req *GetUsersSearchRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByType not implemented")
}
func (*UnimplementedUsersServiceServer) GetStartupUserByID(ctx context.Context, req *Uint32TypeRequest) (*StartupUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStartupUserByID not implemented")
}
func (*UnimplementedUsersServiceServer) GetInvestorUserByID(ctx context.Context, req *Uint32TypeRequest) (*InvestorUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvestorUserByID not implemented")
}
func (*UnimplementedUsersServiceServer) CreateUser(ctx context.Context, req *user.User) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUsersServiceServer) CreateStartupUser(ctx context.Context, req *startup_user.StartupUser) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStartupUser not implemented")
}
func (*UnimplementedUsersServiceServer) CreateInvestorUser(ctx context.Context, req *investor_user.InvestorUser) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvestorUser not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateUser(ctx context.Context, req *user.User) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateStartupUser(ctx context.Context, req *startup_user.StartupUser) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStartupUser not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateInvestorUser(ctx context.Context, req *investor_user.InvestorUser) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvestorUser not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteUser(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteStartupUser(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStartupUser not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteInvestorUser(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInvestorUser not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteProfile(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (*UnimplementedUsersServiceServer) CreateTeam(ctx context.Context, req *team.Team) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateTeam(ctx context.Context, req *team.Team) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteTeam(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedUsersServiceServer) GetTeamById(ctx context.Context, req *Uint32TypeRequest) (*team.Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamById not implemented")
}
func (*UnimplementedUsersServiceServer) GetTeamByName(ctx context.Context, req *StringTypeRequest) (*team.Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamByName not implemented")
}
func (*UnimplementedUsersServiceServer) GetTeamByEmail(ctx context.Context, req *StringTypeRequest) (*team.Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamByEmail not implemented")
}
func (*UnimplementedUsersServiceServer) GetTeamsByType(ctx context.Context, req *StringTypeRequest) (*team.Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByType not implemented")
}
func (*UnimplementedUsersServiceServer) GetTeamsByIndustry(ctx context.Context, req *StringTypeRequest) (*TeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByIndustry not implemented")
}
func (*UnimplementedUsersServiceServer) CreateGroup(ctx context.Context, req *group.Group) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedUsersServiceServer) GetGroupById(ctx context.Context, req *Uint32TypeRequest) (*GroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupById not implemented")
}
func (*UnimplementedUsersServiceServer) GetGroupByName(ctx context.Context, req *Uint32TypeRequest) (*GroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupByName not implemented")
}
func (*UnimplementedUsersServiceServer) GetGroupsByType(ctx context.Context, req *StringTypeRequest) (*GroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupsByType not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateGroup(ctx context.Context, req *group.Group) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteGroup(ctx context.Context, req *Uint32TypeRequest) (*UpdateOrCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserByID(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserByUsername(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserByEmail(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUsersByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUsersByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetUsersByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUsersByType(ctx, req.(*GetUsersSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetStartupUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetStartupUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetStartupUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetStartupUserByID(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetInvestorUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetInvestorUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetInvestorUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetInvestorUserByID(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateStartupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(startup_user.StartupUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateStartupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/CreateStartupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateStartupUser(ctx, req.(*startup_user.StartupUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateInvestorUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(investor_user.InvestorUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateInvestorUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/CreateInvestorUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateInvestorUser(ctx, req.(*investor_user.InvestorUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUser(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateStartupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(startup_user.StartupUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateStartupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/UpdateStartupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateStartupUser(ctx, req.(*startup_user.StartupUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateInvestorUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(investor_user.InvestorUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateInvestorUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/UpdateInvestorUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateInvestorUser(ctx, req.(*investor_user.InvestorUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteStartupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteStartupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteStartupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteStartupUser(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteInvestorUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteInvestorUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteInvestorUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteInvestorUser(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteProfile(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(team.Team)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateTeam(ctx, req.(*team.Team))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(team.Team)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/UpdateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateTeam(ctx, req.(*team.Team))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteTeam(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetTeamById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetTeamById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetTeamById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetTeamById(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetTeamByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetTeamByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetTeamByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetTeamByName(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetTeamByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetTeamByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetTeamByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetTeamByEmail(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetTeamsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetTeamsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetTeamsByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetTeamsByType(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetTeamsByIndustry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetTeamsByIndustry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetTeamsByIndustry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetTeamsByIndustry(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(group.Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateGroup(ctx, req.(*group.Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetGroupById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetGroupById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetGroupById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetGroupById(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetGroupByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetGroupByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetGroupByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetGroupByName(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetGroupsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetGroupsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/GetGroupsByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetGroupsByType(ctx, req.(*StringTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(group.Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateGroup(ctx, req.(*group.Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uint32TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersService.UsersService/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteGroup(ctx, req.(*Uint32TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usersService.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByID",
			Handler:    _UsersService_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByUsername",
			Handler:    _UsersService_GetUserByUsername_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UsersService_GetUserByEmail_Handler,
		},
		{
			MethodName: "GetUsersByType",
			Handler:    _UsersService_GetUsersByType_Handler,
		},
		{
			MethodName: "GetStartupUserByID",
			Handler:    _UsersService_GetStartupUserByID_Handler,
		},
		{
			MethodName: "GetInvestorUserByID",
			Handler:    _UsersService_GetInvestorUserByID_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "CreateStartupUser",
			Handler:    _UsersService_CreateStartupUser_Handler,
		},
		{
			MethodName: "CreateInvestorUser",
			Handler:    _UsersService_CreateInvestorUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateStartupUser",
			Handler:    _UsersService_UpdateStartupUser_Handler,
		},
		{
			MethodName: "UpdateInvestorUser",
			Handler:    _UsersService_UpdateInvestorUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
		{
			MethodName: "DeleteStartupUser",
			Handler:    _UsersService_DeleteStartupUser_Handler,
		},
		{
			MethodName: "DeleteInvestorUser",
			Handler:    _UsersService_DeleteInvestorUser_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _UsersService_DeleteProfile_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _UsersService_CreateTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _UsersService_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _UsersService_DeleteTeam_Handler,
		},
		{
			MethodName: "GetTeamById",
			Handler:    _UsersService_GetTeamById_Handler,
		},
		{
			MethodName: "GetTeamByName",
			Handler:    _UsersService_GetTeamByName_Handler,
		},
		{
			MethodName: "GetTeamByEmail",
			Handler:    _UsersService_GetTeamByEmail_Handler,
		},
		{
			MethodName: "GetTeamsByType",
			Handler:    _UsersService_GetTeamsByType_Handler,
		},
		{
			MethodName: "GetTeamsByIndustry",
			Handler:    _UsersService_GetTeamsByIndustry_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _UsersService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroupById",
			Handler:    _UsersService_GetGroupById_Handler,
		},
		{
			MethodName: "GetGroupByName",
			Handler:    _UsersService_GetGroupByName_Handler,
		},
		{
			MethodName: "GetGroupsByType",
			Handler:    _UsersService_GetGroupsByType_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _UsersService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _UsersService_DeleteGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
