// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Education struct {
	MostRecentInstitutionName string   `protobuf:"bytes,1,opt,name=MostRecentInstitutionName,proto3" json:"MostRecentInstitutionName,omitempty"`
	HighestDegreeEarned       string   `protobuf:"bytes,2,opt,name=HighestDegreeEarned,proto3" json:"HighestDegreeEarned,omitempty"`
	Graduated                 bool     `protobuf:"varint,3,opt,name=Graduated,proto3" json:"Graduated,omitempty"`
	Major                     string   `protobuf:"bytes,4,opt,name=Major,proto3" json:"Major,omitempty"`
	Minor                     string   `protobuf:"bytes,5,opt,name=Minor,proto3" json:"Minor,omitempty"`
	YearsOfAttendance         string   `protobuf:"bytes,6,opt,name=YearsOfAttendance,proto3" json:"YearsOfAttendance,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{1}
}

func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetMostRecentInstitutionName() string {
	if m != nil {
		return m.MostRecentInstitutionName
	}
	return ""
}

func (m *Education) GetHighestDegreeEarned() string {
	if m != nil {
		return m.HighestDegreeEarned
	}
	return ""
}

func (m *Education) GetGraduated() bool {
	if m != nil {
		return m.Graduated
	}
	return false
}

func (m *Education) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *Education) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func (m *Education) GetYearsOfAttendance() string {
	if m != nil {
		return m.YearsOfAttendance
	}
	return ""
}

type Interests struct {
	Industry             []*Industry `protobuf:"bytes,1,rep,name=Industry,proto3" json:"Industry,omitempty"`
	Topic                []*Topic    `protobuf:"bytes,2,rep,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Interests) Reset()         { *m = Interests{} }
func (m *Interests) String() string { return proto.CompactTextString(m) }
func (*Interests) ProtoMessage()    {}
func (*Interests) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{2}
}

func (m *Interests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interests.Unmarshal(m, b)
}
func (m *Interests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interests.Marshal(b, m, deterministic)
}
func (m *Interests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interests.Merge(m, src)
}
func (m *Interests) XXX_Size() int {
	return xxx_messageInfo_Interests.Size(m)
}
func (m *Interests) XXX_DiscardUnknown() {
	xxx_messageInfo_Interests.DiscardUnknown(m)
}

var xxx_messageInfo_Interests proto.InternalMessageInfo

func (m *Interests) GetIndustry() []*Industry {
	if m != nil {
		return m.Industry
	}
	return nil
}

func (m *Interests) GetTopic() []*Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

type Topic struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	TopicType            string   `protobuf:"bytes,2,opt,name=TopicType,proto3" json:"TopicType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{3}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Topic) GetTopicType() string {
	if m != nil {
		return m.TopicType
	}
	return ""
}

type Industry struct {
	IndustryName         string   `protobuf:"bytes,1,opt,name=IndustryName,proto3" json:"IndustryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Industry) Reset()         { *m = Industry{} }
func (m *Industry) String() string { return proto.CompactTextString(m) }
func (*Industry) ProtoMessage()    {}
func (*Industry) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{4}
}

func (m *Industry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Industry.Unmarshal(m, b)
}
func (m *Industry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Industry.Marshal(b, m, deterministic)
}
func (m *Industry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Industry.Merge(m, src)
}
func (m *Industry) XXX_Size() int {
	return xxx_messageInfo_Industry.Size(m)
}
func (m *Industry) XXX_DiscardUnknown() {
	xxx_messageInfo_Industry.DiscardUnknown(m)
}

var xxx_messageInfo_Industry proto.InternalMessageInfo

func (m *Industry) GetIndustryName() string {
	if m != nil {
		return m.IndustryName
	}
	return ""
}

type Subscriptions struct {
	SubscriptionName     string   `protobuf:"bytes,1,opt,name=SubscriptionName,proto3" json:"SubscriptionName,omitempty"`
	Subscribe            bool     `protobuf:"varint,2,opt,name=Subscribe,proto3" json:"Subscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscriptions) Reset()         { *m = Subscriptions{} }
func (m *Subscriptions) String() string { return proto.CompactTextString(m) }
func (*Subscriptions) ProtoMessage()    {}
func (*Subscriptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{5}
}

func (m *Subscriptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscriptions.Unmarshal(m, b)
}
func (m *Subscriptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscriptions.Marshal(b, m, deterministic)
}
func (m *Subscriptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscriptions.Merge(m, src)
}
func (m *Subscriptions) XXX_Size() int {
	return xxx_messageInfo_Subscriptions.Size(m)
}
func (m *Subscriptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscriptions.DiscardUnknown(m)
}

var xxx_messageInfo_Subscriptions proto.InternalMessageInfo

func (m *Subscriptions) GetSubscriptionName() string {
	if m != nil {
		return m.SubscriptionName
	}
	return ""
}

func (m *Subscriptions) GetSubscribe() bool {
	if m != nil {
		return m.Subscribe
	}
	return false
}

type SkillSet struct {
	Skills               []*Skill `protobuf:"bytes,1,rep,name=Skills,proto3" json:"Skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillSet) Reset()         { *m = SkillSet{} }
func (m *SkillSet) String() string { return proto.CompactTextString(m) }
func (*SkillSet) ProtoMessage()    {}
func (*SkillSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{6}
}

func (m *SkillSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillSet.Unmarshal(m, b)
}
func (m *SkillSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillSet.Marshal(b, m, deterministic)
}
func (m *SkillSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillSet.Merge(m, src)
}
func (m *SkillSet) XXX_Size() int {
	return xxx_messageInfo_SkillSet.Size(m)
}
func (m *SkillSet) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillSet.DiscardUnknown(m)
}

var xxx_messageInfo_SkillSet proto.InternalMessageInfo

func (m *SkillSet) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Skill struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{7}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TeamMember struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamMember) Reset()         { *m = TeamMember{} }
func (m *TeamMember) String() string { return proto.CompactTextString(m) }
func (*TeamMember) ProtoMessage()    {}
func (*TeamMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{8}
}

func (m *TeamMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamMember.Unmarshal(m, b)
}
func (m *TeamMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamMember.Marshal(b, m, deterministic)
}
func (m *TeamMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamMember.Merge(m, src)
}
func (m *TeamMember) XXX_Size() int {
	return xxx_messageInfo_TeamMember.Size(m)
}
func (m *TeamMember) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamMember.DiscardUnknown(m)
}

var xxx_messageInfo_TeamMember proto.InternalMessageInfo

func (m *TeamMember) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TeamMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamMember) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TeamMember) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Contact struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{9}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type SocialMedia struct {
	Website              string   `protobuf:"bytes,1,opt,name=Website,proto3" json:"Website,omitempty"`
	Facebook             string   `protobuf:"bytes,2,opt,name=Facebook,proto3" json:"Facebook,omitempty"`
	Twitter              string   `protobuf:"bytes,3,opt,name=Twitter,proto3" json:"Twitter,omitempty"`
	LinkedIn             string   `protobuf:"bytes,4,opt,name=LinkedIn,proto3" json:"LinkedIn,omitempty"`
	Instagram            string   `protobuf:"bytes,5,opt,name=Instagram,proto3" json:"Instagram,omitempty"`
	Youtube              string   `protobuf:"bytes,6,opt,name=Youtube,proto3" json:"Youtube,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialMedia) Reset()         { *m = SocialMedia{} }
func (m *SocialMedia) String() string { return proto.CompactTextString(m) }
func (*SocialMedia) ProtoMessage()    {}
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{10}
}

func (m *SocialMedia) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialMedia.Unmarshal(m, b)
}
func (m *SocialMedia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialMedia.Marshal(b, m, deterministic)
}
func (m *SocialMedia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialMedia.Merge(m, src)
}
func (m *SocialMedia) XXX_Size() int {
	return xxx_messageInfo_SocialMedia.Size(m)
}
func (m *SocialMedia) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialMedia.DiscardUnknown(m)
}

var xxx_messageInfo_SocialMedia proto.InternalMessageInfo

func (m *SocialMedia) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *SocialMedia) GetFacebook() string {
	if m != nil {
		return m.Facebook
	}
	return ""
}

func (m *SocialMedia) GetTwitter() string {
	if m != nil {
		return m.Twitter
	}
	return ""
}

func (m *SocialMedia) GetLinkedIn() string {
	if m != nil {
		return m.LinkedIn
	}
	return ""
}

func (m *SocialMedia) GetInstagram() string {
	if m != nil {
		return m.Instagram
	}
	return ""
}

func (m *SocialMedia) GetYoutube() string {
	if m != nil {
		return m.Youtube
	}
	return ""
}

type Funding struct {
	TotalFunding         int32         `protobuf:"varint,1,opt,name=TotalFunding,proto3" json:"TotalFunding,omitempty"`
	LatestRound          string        `protobuf:"bytes,2,opt,name=LatestRound,proto3" json:"LatestRound,omitempty"`
	LatestRoundDate      string        `protobuf:"bytes,3,opt,name=LatestRoundDate,proto3" json:"LatestRoundDate,omitempty"`
	LatestRoundFunding   int32         `protobuf:"varint,4,opt,name=LatestRoundFunding,proto3" json:"LatestRoundFunding,omitempty"`
	Investors            []*TeamMember `protobuf:"bytes,5,rep,name=Investors,proto3" json:"Investors,omitempty"`
	InvestorType         string        `protobuf:"bytes,6,opt,name=InvestorType,proto3" json:"InvestorType,omitempty"`
	InvestmentStage      string        `protobuf:"bytes,7,opt,name=InvestmentStage,proto3" json:"InvestmentStage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Funding) Reset()         { *m = Funding{} }
func (m *Funding) String() string { return proto.CompactTextString(m) }
func (*Funding) ProtoMessage()    {}
func (*Funding) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{11}
}

func (m *Funding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Funding.Unmarshal(m, b)
}
func (m *Funding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Funding.Marshal(b, m, deterministic)
}
func (m *Funding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Funding.Merge(m, src)
}
func (m *Funding) XXX_Size() int {
	return xxx_messageInfo_Funding.Size(m)
}
func (m *Funding) XXX_DiscardUnknown() {
	xxx_messageInfo_Funding.DiscardUnknown(m)
}

var xxx_messageInfo_Funding proto.InternalMessageInfo

func (m *Funding) GetTotalFunding() int32 {
	if m != nil {
		return m.TotalFunding
	}
	return 0
}

func (m *Funding) GetLatestRound() string {
	if m != nil {
		return m.LatestRound
	}
	return ""
}

func (m *Funding) GetLatestRoundDate() string {
	if m != nil {
		return m.LatestRoundDate
	}
	return ""
}

func (m *Funding) GetLatestRoundFunding() int32 {
	if m != nil {
		return m.LatestRoundFunding
	}
	return 0
}

func (m *Funding) GetInvestors() []*TeamMember {
	if m != nil {
		return m.Investors
	}
	return nil
}

func (m *Funding) GetInvestorType() string {
	if m != nil {
		return m.InvestorType
	}
	return ""
}

func (m *Funding) GetInvestmentStage() string {
	if m != nil {
		return m.InvestmentStage
	}
	return ""
}

type Details struct {
	IPOStatus            string   `protobuf:"bytes,1,opt,name=IPOStatus,proto3" json:"IPOStatus,omitempty"`
	CompanyType          string   `protobuf:"bytes,2,opt,name=CompanyType,proto3" json:"CompanyType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{12}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetIPOStatus() string {
	if m != nil {
		return m.IPOStatus
	}
	return ""
}

func (m *Details) GetCompanyType() string {
	if m != nil {
		return m.CompanyType
	}
	return ""
}

type Experience struct {
	CompanyName          string   `protobuf:"bytes,1,opt,name=CompanyName,proto3" json:"CompanyName,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Experience) Reset()         { *m = Experience{} }
func (m *Experience) String() string { return proto.CompactTextString(m) }
func (*Experience) ProtoMessage()    {}
func (*Experience) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{13}
}

func (m *Experience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experience.Unmarshal(m, b)
}
func (m *Experience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experience.Marshal(b, m, deterministic)
}
func (m *Experience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experience.Merge(m, src)
}
func (m *Experience) XXX_Size() int {
	return xxx_messageInfo_Experience.Size(m)
}
func (m *Experience) XXX_DiscardUnknown() {
	xxx_messageInfo_Experience.DiscardUnknown(m)
}

var xxx_messageInfo_Experience proto.InternalMessageInfo

func (m *Experience) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *Experience) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Experience) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Experience) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Investment struct {
	CompanyName          string   `protobuf:"bytes,1,opt,name=CompanyName,proto3" json:"CompanyName,omitempty"`
	Industry             string   `protobuf:"bytes,2,opt,name=Industry,proto3" json:"Industry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Investment) Reset()         { *m = Investment{} }
func (m *Investment) String() string { return proto.CompactTextString(m) }
func (*Investment) ProtoMessage()    {}
func (*Investment) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{14}
}

func (m *Investment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Investment.Unmarshal(m, b)
}
func (m *Investment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Investment.Marshal(b, m, deterministic)
}
func (m *Investment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Investment.Merge(m, src)
}
func (m *Investment) XXX_Size() int {
	return xxx_messageInfo_Investment.Size(m)
}
func (m *Investment) XXX_DiscardUnknown() {
	xxx_messageInfo_Investment.DiscardUnknown(m)
}

var xxx_messageInfo_Investment proto.InternalMessageInfo

func (m *Investment) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *Investment) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

type InvestorDetails struct {
	TeamID               uint32               `protobuf:"varint,1,opt,name=TeamID,proto3" json:"TeamID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	InvestorType         string               `protobuf:"bytes,4,opt,name=InvestorType,proto3" json:"InvestorType,omitempty"`
	InvestmentStage      string               `protobuf:"bytes,5,opt,name=InvestmentStage,proto3" json:"InvestmentStage,omitempty"`
	NumberOfExits        int32                `protobuf:"varint,6,opt,name=NumberOfExits,proto3" json:"NumberOfExits,omitempty"`
	NumberOfinvestments  int32                `protobuf:"varint,7,opt,name=NumberOfinvestments,proto3" json:"NumberOfinvestments,omitempty"`
	NumberOfFunds        int32                `protobuf:"varint,8,opt,name=NumberOfFunds,proto3" json:"NumberOfFunds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InvestorDetails) Reset()         { *m = InvestorDetails{} }
func (m *InvestorDetails) String() string { return proto.CompactTextString(m) }
func (*InvestorDetails) ProtoMessage()    {}
func (*InvestorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{15}
}

func (m *InvestorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvestorDetails.Unmarshal(m, b)
}
func (m *InvestorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvestorDetails.Marshal(b, m, deterministic)
}
func (m *InvestorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvestorDetails.Merge(m, src)
}
func (m *InvestorDetails) XXX_Size() int {
	return xxx_messageInfo_InvestorDetails.Size(m)
}
func (m *InvestorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_InvestorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_InvestorDetails proto.InternalMessageInfo

func (m *InvestorDetails) GetTeamID() uint32 {
	if m != nil {
		return m.TeamID
	}
	return 0
}

func (m *InvestorDetails) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *InvestorDetails) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *InvestorDetails) GetInvestorType() string {
	if m != nil {
		return m.InvestorType
	}
	return ""
}

func (m *InvestorDetails) GetInvestmentStage() string {
	if m != nil {
		return m.InvestmentStage
	}
	return ""
}

func (m *InvestorDetails) GetNumberOfExits() int32 {
	if m != nil {
		return m.NumberOfExits
	}
	return 0
}

func (m *InvestorDetails) GetNumberOfinvestments() int32 {
	if m != nil {
		return m.NumberOfinvestments
	}
	return 0
}

func (m *InvestorDetails) GetNumberOfFunds() int32 {
	if m != nil {
		return m.NumberOfFunds
	}
	return 0
}

type StartupDetails struct {
	TeamID               uint32               `protobuf:"varint,1,opt,name=TeamID,proto3" json:"TeamID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Funding              *Funding             `protobuf:"bytes,4,opt,name=Funding,proto3" json:"Funding,omitempty"`
	CompanyDetails       *Details             `protobuf:"bytes,5,opt,name=CompanyDetails,proto3" json:"CompanyDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StartupDetails) Reset()         { *m = StartupDetails{} }
func (m *StartupDetails) String() string { return proto.CompactTextString(m) }
func (*StartupDetails) ProtoMessage()    {}
func (*StartupDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{16}
}

func (m *StartupDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupDetails.Unmarshal(m, b)
}
func (m *StartupDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupDetails.Marshal(b, m, deterministic)
}
func (m *StartupDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupDetails.Merge(m, src)
}
func (m *StartupDetails) XXX_Size() int {
	return xxx_messageInfo_StartupDetails.Size(m)
}
func (m *StartupDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupDetails.DiscardUnknown(m)
}

var xxx_messageInfo_StartupDetails proto.InternalMessageInfo

func (m *StartupDetails) GetTeamID() uint32 {
	if m != nil {
		return m.TeamID
	}
	return 0
}

func (m *StartupDetails) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *StartupDetails) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *StartupDetails) GetFunding() *Funding {
	if m != nil {
		return m.Funding
	}
	return nil
}

func (m *StartupDetails) GetCompanyDetails() *Details {
	if m != nil {
		return m.CompanyDetails
	}
	return nil
}

type Settings struct {
	Notifications        *Notification `protobuf:"bytes,1,opt,name=Notifications,proto3" json:"Notifications,omitempty"`
	Privacy              *Privacy      `protobuf:"bytes,2,opt,name=Privacy,proto3" json:"Privacy,omitempty"`
	Payment              *Payments     `protobuf:"bytes,3,opt,name=Payment,proto3" json:"Payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{17}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

func (m *Settings) GetNotifications() *Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *Settings) GetPrivacy() *Privacy {
	if m != nil {
		return m.Privacy
	}
	return nil
}

func (m *Settings) GetPayment() *Payments {
	if m != nil {
		return m.Payment
	}
	return nil
}

type Payments struct {
	Debit                *Card    `protobuf:"bytes,1,opt,name=Debit,proto3" json:"Debit,omitempty"`
	Credit               *Card    `protobuf:"bytes,2,opt,name=Credit,proto3" json:"Credit,omitempty"`
	SecurityPin          *Pin     `protobuf:"bytes,3,opt,name=SecurityPin,proto3" json:"SecurityPin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payments) Reset()         { *m = Payments{} }
func (m *Payments) String() string { return proto.CompactTextString(m) }
func (*Payments) ProtoMessage()    {}
func (*Payments) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{18}
}

func (m *Payments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payments.Unmarshal(m, b)
}
func (m *Payments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payments.Marshal(b, m, deterministic)
}
func (m *Payments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payments.Merge(m, src)
}
func (m *Payments) XXX_Size() int {
	return xxx_messageInfo_Payments.Size(m)
}
func (m *Payments) XXX_DiscardUnknown() {
	xxx_messageInfo_Payments.DiscardUnknown(m)
}

var xxx_messageInfo_Payments proto.InternalMessageInfo

func (m *Payments) GetDebit() *Card {
	if m != nil {
		return m.Debit
	}
	return nil
}

func (m *Payments) GetCredit() *Card {
	if m != nil {
		return m.Credit
	}
	return nil
}

func (m *Payments) GetSecurityPin() *Pin {
	if m != nil {
		return m.SecurityPin
	}
	return nil
}

type Card struct {
	CardNumber           string   `protobuf:"bytes,1,opt,name=CardNumber,proto3" json:"CardNumber,omitempty"`
	SecurityCode         string   `protobuf:"bytes,2,opt,name=SecurityCode,proto3" json:"SecurityCode,omitempty"`
	CardZipCode          string   `protobuf:"bytes,3,opt,name=CardZipCode,proto3" json:"CardZipCode,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"State,omitempty"`
	ZipCode              string   `protobuf:"bytes,8,opt,name=ZipCode,proto3" json:"ZipCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{19}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *Card) GetSecurityCode() string {
	if m != nil {
		return m.SecurityCode
	}
	return ""
}

func (m *Card) GetCardZipCode() string {
	if m != nil {
		return m.CardZipCode
	}
	return ""
}

func (m *Card) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Card) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Card) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Card) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Card) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

type Pin struct {
	PinEnabled           bool     `protobuf:"varint,1,opt,name=PinEnabled,proto3" json:"PinEnabled,omitempty"`
	Pin                  string   `protobuf:"bytes,2,opt,name=Pin,proto3" json:"Pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pin) Reset()         { *m = Pin{} }
func (m *Pin) String() string { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()    {}
func (*Pin) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{20}
}

func (m *Pin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pin.Unmarshal(m, b)
}
func (m *Pin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pin.Marshal(b, m, deterministic)
}
func (m *Pin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pin.Merge(m, src)
}
func (m *Pin) XXX_Size() int {
	return xxx_messageInfo_Pin.Size(m)
}
func (m *Pin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pin.DiscardUnknown(m)
}

var xxx_messageInfo_Pin proto.InternalMessageInfo

func (m *Pin) GetPinEnabled() bool {
	if m != nil {
		return m.PinEnabled
	}
	return false
}

func (m *Pin) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type Privacy struct {
	ActivityStatus       bool     `protobuf:"varint,1,opt,name=ActivityStatus,proto3" json:"ActivityStatus,omitempty"`
	PrivateAccount       bool     `protobuf:"varint,2,opt,name=PrivateAccount,proto3" json:"PrivateAccount,omitempty"`
	BlockedAccountIds    []string `protobuf:"bytes,3,rep,name=BlockedAccountIds,proto3" json:"BlockedAccountIds,omitempty"`
	MutedAccountIds      []string `protobuf:"bytes,4,rep,name=MutedAccountIds,proto3" json:"MutedAccountIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Privacy) Reset()         { *m = Privacy{} }
func (m *Privacy) String() string { return proto.CompactTextString(m) }
func (*Privacy) ProtoMessage()    {}
func (*Privacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{21}
}

func (m *Privacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Privacy.Unmarshal(m, b)
}
func (m *Privacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Privacy.Marshal(b, m, deterministic)
}
func (m *Privacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Privacy.Merge(m, src)
}
func (m *Privacy) XXX_Size() int {
	return xxx_messageInfo_Privacy.Size(m)
}
func (m *Privacy) XXX_DiscardUnknown() {
	xxx_messageInfo_Privacy.DiscardUnknown(m)
}

var xxx_messageInfo_Privacy proto.InternalMessageInfo

func (m *Privacy) GetActivityStatus() bool {
	if m != nil {
		return m.ActivityStatus
	}
	return false
}

func (m *Privacy) GetPrivateAccount() bool {
	if m != nil {
		return m.PrivateAccount
	}
	return false
}

func (m *Privacy) GetBlockedAccountIds() []string {
	if m != nil {
		return m.BlockedAccountIds
	}
	return nil
}

func (m *Privacy) GetMutedAccountIds() []string {
	if m != nil {
		return m.MutedAccountIds
	}
	return nil
}

type Notification struct {
	PauseAll              bool                                           `protobuf:"varint,1,opt,name=PauseAll,proto3" json:"PauseAll,omitempty"`
	PostsAndComments      *PostAndCommentsPushNotificationSettings       `protobuf:"bytes,2,opt,name=PostsAndComments,proto3" json:"PostsAndComments,omitempty"`
	FollowingAndFollowers *FollowingAndFollowersPushNotificationSettings `protobuf:"bytes,3,opt,name=FollowingAndFollowers,proto3" json:"FollowingAndFollowers,omitempty"`
	DirectMessages        *DirectMessagesPushNotificationSettings        `protobuf:"bytes,4,opt,name=DirectMessages,proto3" json:"DirectMessages,omitempty"`
	EmailAndSms           *EmailAndSmsPushNotificationSettings           `protobuf:"bytes,5,opt,name=EmailAndSms,proto3" json:"EmailAndSms,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                       `json:"-"`
	XXX_unrecognized      []byte                                         `json:"-"`
	XXX_sizecache         int32                                          `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{22}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetPauseAll() bool {
	if m != nil {
		return m.PauseAll
	}
	return false
}

func (m *Notification) GetPostsAndComments() *PostAndCommentsPushNotificationSettings {
	if m != nil {
		return m.PostsAndComments
	}
	return nil
}

func (m *Notification) GetFollowingAndFollowers() *FollowingAndFollowersPushNotificationSettings {
	if m != nil {
		return m.FollowingAndFollowers
	}
	return nil
}

func (m *Notification) GetDirectMessages() *DirectMessagesPushNotificationSettings {
	if m != nil {
		return m.DirectMessages
	}
	return nil
}

func (m *Notification) GetEmailAndSms() *EmailAndSmsPushNotificationSettings {
	if m != nil {
		return m.EmailAndSms
	}
	return nil
}

type PostAndCommentsPushNotificationSettings struct {
	Likes                        *TieredPushNotificationSetting `protobuf:"bytes,1,opt,name=Likes,proto3" json:"Likes,omitempty"`
	LikesAndCommentsOnPostsOfYou *TieredPushNotificationSetting `protobuf:"bytes,2,opt,name=LikesAndCommentsOnPostsOfYou,proto3" json:"LikesAndCommentsOnPostsOfYou,omitempty"`
	PostsOfYou                   *TieredPushNotificationSetting `protobuf:"bytes,3,opt,name=PostsOfYou,proto3" json:"PostsOfYou,omitempty"`
	Comments                     *TieredPushNotificationSetting `protobuf:"bytes,4,opt,name=Comments,proto3" json:"Comments,omitempty"`
	CommentLikes                 *TieredPushNotificationSetting `protobuf:"bytes,5,opt,name=CommentLikes,proto3" json:"CommentLikes,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                       `json:"-"`
	XXX_unrecognized             []byte                         `json:"-"`
	XXX_sizecache                int32                          `json:"-"`
}

func (m *PostAndCommentsPushNotificationSettings) Reset() {
	*m = PostAndCommentsPushNotificationSettings{}
}
func (m *PostAndCommentsPushNotificationSettings) String() string { return proto.CompactTextString(m) }
func (*PostAndCommentsPushNotificationSettings) ProtoMessage()    {}
func (*PostAndCommentsPushNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{23}
}

func (m *PostAndCommentsPushNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAndCommentsPushNotificationSettings.Unmarshal(m, b)
}
func (m *PostAndCommentsPushNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAndCommentsPushNotificationSettings.Marshal(b, m, deterministic)
}
func (m *PostAndCommentsPushNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAndCommentsPushNotificationSettings.Merge(m, src)
}
func (m *PostAndCommentsPushNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_PostAndCommentsPushNotificationSettings.Size(m)
}
func (m *PostAndCommentsPushNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAndCommentsPushNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_PostAndCommentsPushNotificationSettings proto.InternalMessageInfo

func (m *PostAndCommentsPushNotificationSettings) GetLikes() *TieredPushNotificationSetting {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *PostAndCommentsPushNotificationSettings) GetLikesAndCommentsOnPostsOfYou() *TieredPushNotificationSetting {
	if m != nil {
		return m.LikesAndCommentsOnPostsOfYou
	}
	return nil
}

func (m *PostAndCommentsPushNotificationSettings) GetPostsOfYou() *TieredPushNotificationSetting {
	if m != nil {
		return m.PostsOfYou
	}
	return nil
}

func (m *PostAndCommentsPushNotificationSettings) GetComments() *TieredPushNotificationSetting {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *PostAndCommentsPushNotificationSettings) GetCommentLikes() *TieredPushNotificationSetting {
	if m != nil {
		return m.CommentLikes
	}
	return nil
}

type FollowingAndFollowersPushNotificationSettings struct {
	FollowerRequests         *PushNotificationSetting       `protobuf:"bytes,1,opt,name=FollowerRequests,proto3" json:"FollowerRequests,omitempty"`
	AcceptedFollowerRequests *PushNotificationSetting       `protobuf:"bytes,2,opt,name=AcceptedFollowerRequests,proto3" json:"AcceptedFollowerRequests,omitempty"`
	MentionsInBio            *TieredPushNotificationSetting `protobuf:"bytes,3,opt,name=MentionsInBio,proto3" json:"MentionsInBio,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                       `json:"-"`
	XXX_unrecognized         []byte                         `json:"-"`
	XXX_sizecache            int32                          `json:"-"`
}

func (m *FollowingAndFollowersPushNotificationSettings) Reset() {
	*m = FollowingAndFollowersPushNotificationSettings{}
}
func (m *FollowingAndFollowersPushNotificationSettings) String() string {
	return proto.CompactTextString(m)
}
func (*FollowingAndFollowersPushNotificationSettings) ProtoMessage() {}
func (*FollowingAndFollowersPushNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{24}
}

func (m *FollowingAndFollowersPushNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingAndFollowersPushNotificationSettings.Unmarshal(m, b)
}
func (m *FollowingAndFollowersPushNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingAndFollowersPushNotificationSettings.Marshal(b, m, deterministic)
}
func (m *FollowingAndFollowersPushNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingAndFollowersPushNotificationSettings.Merge(m, src)
}
func (m *FollowingAndFollowersPushNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_FollowingAndFollowersPushNotificationSettings.Size(m)
}
func (m *FollowingAndFollowersPushNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingAndFollowersPushNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingAndFollowersPushNotificationSettings proto.InternalMessageInfo

func (m *FollowingAndFollowersPushNotificationSettings) GetFollowerRequests() *PushNotificationSetting {
	if m != nil {
		return m.FollowerRequests
	}
	return nil
}

func (m *FollowingAndFollowersPushNotificationSettings) GetAcceptedFollowerRequests() *PushNotificationSetting {
	if m != nil {
		return m.AcceptedFollowerRequests
	}
	return nil
}

func (m *FollowingAndFollowersPushNotificationSettings) GetMentionsInBio() *TieredPushNotificationSetting {
	if m != nil {
		return m.MentionsInBio
	}
	return nil
}

type DirectMessagesPushNotificationSettings struct {
	MessageRequests      *PushNotificationSetting `protobuf:"bytes,1,opt,name=MessageRequests,proto3" json:"MessageRequests,omitempty"`
	Message              *PushNotificationSetting `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	GroupRequests        *PushNotificationSetting `protobuf:"bytes,3,opt,name=GroupRequests,proto3" json:"GroupRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DirectMessagesPushNotificationSettings) Reset() {
	*m = DirectMessagesPushNotificationSettings{}
}
func (m *DirectMessagesPushNotificationSettings) String() string { return proto.CompactTextString(m) }
func (*DirectMessagesPushNotificationSettings) ProtoMessage()    {}
func (*DirectMessagesPushNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{25}
}

func (m *DirectMessagesPushNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectMessagesPushNotificationSettings.Unmarshal(m, b)
}
func (m *DirectMessagesPushNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectMessagesPushNotificationSettings.Marshal(b, m, deterministic)
}
func (m *DirectMessagesPushNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectMessagesPushNotificationSettings.Merge(m, src)
}
func (m *DirectMessagesPushNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_DirectMessagesPushNotificationSettings.Size(m)
}
func (m *DirectMessagesPushNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectMessagesPushNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_DirectMessagesPushNotificationSettings proto.InternalMessageInfo

func (m *DirectMessagesPushNotificationSettings) GetMessageRequests() *PushNotificationSetting {
	if m != nil {
		return m.MessageRequests
	}
	return nil
}

func (m *DirectMessagesPushNotificationSettings) GetMessage() *PushNotificationSetting {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DirectMessagesPushNotificationSettings) GetGroupRequests() *PushNotificationSetting {
	if m != nil {
		return m.GroupRequests
	}
	return nil
}

type EmailAndSmsPushNotificationSettings struct {
	FeedbackEmail        *PushNotificationSetting `protobuf:"bytes,1,opt,name=FeedbackEmail,proto3" json:"FeedbackEmail,omitempty"`
	ReminderEmails       *PushNotificationSetting `protobuf:"bytes,2,opt,name=ReminderEmails,proto3" json:"ReminderEmails,omitempty"`
	ProductEmails        *PushNotificationSetting `protobuf:"bytes,3,opt,name=ProductEmails,proto3" json:"ProductEmails,omitempty"`
	NewsEmails           *PushNotificationSetting `protobuf:"bytes,4,opt,name=NewsEmails,proto3" json:"NewsEmails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EmailAndSmsPushNotificationSettings) Reset()         { *m = EmailAndSmsPushNotificationSettings{} }
func (m *EmailAndSmsPushNotificationSettings) String() string { return proto.CompactTextString(m) }
func (*EmailAndSmsPushNotificationSettings) ProtoMessage()    {}
func (*EmailAndSmsPushNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{26}
}

func (m *EmailAndSmsPushNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAndSmsPushNotificationSettings.Unmarshal(m, b)
}
func (m *EmailAndSmsPushNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAndSmsPushNotificationSettings.Marshal(b, m, deterministic)
}
func (m *EmailAndSmsPushNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAndSmsPushNotificationSettings.Merge(m, src)
}
func (m *EmailAndSmsPushNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_EmailAndSmsPushNotificationSettings.Size(m)
}
func (m *EmailAndSmsPushNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAndSmsPushNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAndSmsPushNotificationSettings proto.InternalMessageInfo

func (m *EmailAndSmsPushNotificationSettings) GetFeedbackEmail() *PushNotificationSetting {
	if m != nil {
		return m.FeedbackEmail
	}
	return nil
}

func (m *EmailAndSmsPushNotificationSettings) GetReminderEmails() *PushNotificationSetting {
	if m != nil {
		return m.ReminderEmails
	}
	return nil
}

func (m *EmailAndSmsPushNotificationSettings) GetProductEmails() *PushNotificationSetting {
	if m != nil {
		return m.ProductEmails
	}
	return nil
}

func (m *EmailAndSmsPushNotificationSettings) GetNewsEmails() *PushNotificationSetting {
	if m != nil {
		return m.NewsEmails
	}
	return nil
}

type TieredPushNotificationSetting struct {
	Off                  bool     `protobuf:"varint,1,opt,name=Off,proto3" json:"Off,omitempty"`
	FromPeopleIFollow    bool     `protobuf:"varint,2,opt,name=FromPeopleIFollow,proto3" json:"FromPeopleIFollow,omitempty"`
	FromEveryone         bool     `protobuf:"varint,3,opt,name=FromEveryone,proto3" json:"FromEveryone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TieredPushNotificationSetting) Reset()         { *m = TieredPushNotificationSetting{} }
func (m *TieredPushNotificationSetting) String() string { return proto.CompactTextString(m) }
func (*TieredPushNotificationSetting) ProtoMessage()    {}
func (*TieredPushNotificationSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{27}
}

func (m *TieredPushNotificationSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TieredPushNotificationSetting.Unmarshal(m, b)
}
func (m *TieredPushNotificationSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TieredPushNotificationSetting.Marshal(b, m, deterministic)
}
func (m *TieredPushNotificationSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TieredPushNotificationSetting.Merge(m, src)
}
func (m *TieredPushNotificationSetting) XXX_Size() int {
	return xxx_messageInfo_TieredPushNotificationSetting.Size(m)
}
func (m *TieredPushNotificationSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_TieredPushNotificationSetting.DiscardUnknown(m)
}

var xxx_messageInfo_TieredPushNotificationSetting proto.InternalMessageInfo

func (m *TieredPushNotificationSetting) GetOff() bool {
	if m != nil {
		return m.Off
	}
	return false
}

func (m *TieredPushNotificationSetting) GetFromPeopleIFollow() bool {
	if m != nil {
		return m.FromPeopleIFollow
	}
	return false
}

func (m *TieredPushNotificationSetting) GetFromEveryone() bool {
	if m != nil {
		return m.FromEveryone
	}
	return false
}

type PushNotificationSetting struct {
	Off                  bool     `protobuf:"varint,1,opt,name=Off,proto3" json:"Off,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=On,proto3" json:"On,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushNotificationSetting) Reset()         { *m = PushNotificationSetting{} }
func (m *PushNotificationSetting) String() string { return proto.CompactTextString(m) }
func (*PushNotificationSetting) ProtoMessage()    {}
func (*PushNotificationSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{28}
}

func (m *PushNotificationSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNotificationSetting.Unmarshal(m, b)
}
func (m *PushNotificationSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNotificationSetting.Marshal(b, m, deterministic)
}
func (m *PushNotificationSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNotificationSetting.Merge(m, src)
}
func (m *PushNotificationSetting) XXX_Size() int {
	return xxx_messageInfo_PushNotificationSetting.Size(m)
}
func (m *PushNotificationSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNotificationSetting.DiscardUnknown(m)
}

var xxx_messageInfo_PushNotificationSetting proto.InternalMessageInfo

func (m *PushNotificationSetting) GetOff() bool {
	if m != nil {
		return m.Off
	}
	return false
}

func (m *PushNotificationSetting) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func init() {
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*Education)(nil), "Education")
	proto.RegisterType((*Interests)(nil), "Interests")
	proto.RegisterType((*Topic)(nil), "Topic")
	proto.RegisterType((*Industry)(nil), "Industry")
	proto.RegisterType((*Subscriptions)(nil), "Subscriptions")
	proto.RegisterType((*SkillSet)(nil), "SkillSet")
	proto.RegisterType((*Skill)(nil), "Skill")
	proto.RegisterType((*TeamMember)(nil), "TeamMember")
	proto.RegisterType((*Contact)(nil), "Contact")
	proto.RegisterType((*SocialMedia)(nil), "SocialMedia")
	proto.RegisterType((*Funding)(nil), "Funding")
	proto.RegisterType((*Details)(nil), "Details")
	proto.RegisterType((*Experience)(nil), "Experience")
	proto.RegisterType((*Investment)(nil), "Investment")
	proto.RegisterType((*InvestorDetails)(nil), "InvestorDetails")
	proto.RegisterType((*StartupDetails)(nil), "StartupDetails")
	proto.RegisterType((*Settings)(nil), "Settings")
	proto.RegisterType((*Payments)(nil), "Payments")
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*Pin)(nil), "Pin")
	proto.RegisterType((*Privacy)(nil), "Privacy")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*PostAndCommentsPushNotificationSettings)(nil), "PostAndCommentsPushNotificationSettings")
	proto.RegisterType((*FollowingAndFollowersPushNotificationSettings)(nil), "FollowingAndFollowersPushNotificationSettings")
	proto.RegisterType((*DirectMessagesPushNotificationSettings)(nil), "DirectMessagesPushNotificationSettings")
	proto.RegisterType((*EmailAndSmsPushNotificationSettings)(nil), "EmailAndSmsPushNotificationSettings")
	proto.RegisterType((*TieredPushNotificationSetting)(nil), "TieredPushNotificationSetting")
	proto.RegisterType((*PushNotificationSetting)(nil), "PushNotificationSetting")
}

func init() { proto.RegisterFile("proto/common/common.proto", fileDescriptor_856864ca6250a18a) }

var fileDescriptor_856864ca6250a18a = []byte{
	// 1631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5f, 0x8f, 0x1b, 0x49,
	0x11, 0x97, 0xff, 0x7b, 0xcb, 0xd9, 0xbd, 0xd0, 0xfc, 0xf3, 0x85, 0x5c, 0x88, 0xe6, 0x8e, 0x5c,
	0x38, 0xc1, 0xe4, 0xb4, 0x87, 0xc4, 0x09, 0xd0, 0x09, 0xc7, 0xde, 0x3d, 0x8c, 0xb2, 0xb1, 0x35,
	0x36, 0x42, 0xb9, 0xb7, 0xf6, 0x4c, 0xad, 0xd3, 0xec, 0xb8, 0xdb, 0x74, 0xf7, 0x6c, 0xce, 0x12,
	0x6f, 0x79, 0xe1, 0x95, 0x8f, 0x00, 0xdf, 0x80, 0x6f, 0xc4, 0x13, 0x12, 0xaf, 0xf0, 0x01, 0x40,
	0xdd, 0xd3, 0xed, 0x19, 0xff, 0xd9, 0xd8, 0xbc, 0xdd, 0x93, 0xbb, 0x7e, 0xf5, 0xaf, 0xab, 0xba,
	0xaa, 0xba, 0xc7, 0xf0, 0xfe, 0x52, 0x0a, 0x2d, 0x9e, 0xc5, 0x62, 0xb1, 0x10, 0xdc, 0xfd, 0x84,
	0x16, 0x7b, 0xf0, 0xc3, 0xb9, 0x10, 0xf3, 0x14, 0x9f, 0x59, 0x6a, 0x96, 0x5d, 0x3f, 0xd3, 0x6c,
	0x81, 0x4a, 0xd3, 0xc5, 0x32, 0x17, 0x08, 0xae, 0xa0, 0xd5, 0x4b, 0x12, 0x89, 0x4a, 0x11, 0x02,
	0xf5, 0x3e, 0xd3, 0xab, 0x6e, 0xe5, 0x71, 0xe5, 0xe9, 0x49, 0x64, 0xd7, 0xe4, 0x3b, 0xd0, 0x98,
	0x68, 0xaa, 0xb1, 0x5b, 0xb5, 0x60, 0x4e, 0x90, 0x2e, 0xb4, 0xfa, 0x22, 0xe3, 0x5a, 0xae, 0xba,
	0x35, 0x8b, 0x7b, 0x32, 0xf8, 0x4f, 0x05, 0x4e, 0x2e, 0x92, 0x2c, 0xa6, 0x9a, 0x09, 0x4e, 0x7e,
	0x05, 0xef, 0x5f, 0x09, 0xa5, 0x23, 0x8c, 0x91, 0xeb, 0x21, 0x57, 0x9a, 0xe9, 0xcc, 0x30, 0x5e,
	0xd2, 0x05, 0x3a, 0x37, 0x77, 0x0b, 0x90, 0x4f, 0xe1, 0xdb, 0xbf, 0x61, 0xf3, 0xd7, 0xa8, 0xf4,
	0x00, 0xe7, 0x12, 0xf1, 0x82, 0x4a, 0x8e, 0x89, 0xdb, 0xc9, 0x3e, 0x16, 0x79, 0x08, 0x27, 0x5f,
	0x4a, 0x9a, 0x64, 0x54, 0x63, 0x62, 0x77, 0xd6, 0x8e, 0x0a, 0xc0, 0xc4, 0x72, 0x45, 0xff, 0x20,
	0x64, 0xb7, 0x9e, 0xc7, 0x62, 0x09, 0x8b, 0x32, 0x2e, 0x64, 0xb7, 0xe1, 0x50, 0x43, 0x90, 0x9f,
	0xc0, 0xb7, 0x5e, 0x21, 0x95, 0x6a, 0x74, 0xdd, 0xd3, 0x1a, 0x79, 0x42, 0x79, 0x8c, 0xdd, 0xa6,
	0x95, 0xd8, 0x65, 0x04, 0x63, 0x38, 0x19, 0x72, 0x8d, 0x12, 0x95, 0x56, 0xe4, 0x47, 0xd0, 0x1e,
	0xf2, 0x24, 0x53, 0x26, 0x3b, 0x95, 0xc7, 0xb5, 0xa7, 0x9d, 0xf3, 0x93, 0xd0, 0x03, 0xd1, 0x9a,
	0x45, 0x1e, 0x42, 0x63, 0x2a, 0x96, 0x2c, 0xee, 0x56, 0xad, 0x4c, 0x33, 0xb4, 0x54, 0x94, 0x83,
	0x41, 0xdf, 0x71, 0x4d, 0x48, 0x76, 0x51, 0x4a, 0x59, 0x01, 0xac, 0xb9, 0xd3, 0xd5, 0xd2, 0x1f,
	0x51, 0x01, 0x04, 0x61, 0xb1, 0x13, 0x12, 0xc0, 0x3d, 0xbf, 0x2e, 0x99, 0xda, 0xc0, 0x82, 0x57,
	0x70, 0x3a, 0xc9, 0x66, 0x2a, 0x96, 0x6c, 0x69, 0x0e, 0x41, 0x91, 0x4f, 0xe0, 0x7e, 0x19, 0x28,
	0x29, 0xee, 0xe0, 0x66, 0x2b, 0x0e, 0x9b, 0xe5, 0x5b, 0x69, 0x47, 0x05, 0x10, 0x7c, 0x02, 0xed,
	0xc9, 0x0d, 0x4b, 0xd3, 0x09, 0x6a, 0xf2, 0x08, 0x9a, 0x76, 0xad, 0x5c, 0x7a, 0x9a, 0xa1, 0x25,
	0x23, 0x87, 0x06, 0xcf, 0xa0, 0x61, 0x57, 0xa6, 0x20, 0x6d, 0x60, 0xae, 0x20, 0xcd, 0xda, 0x60,
	0x76, 0x1b, 0x79, 0xb0, 0x76, 0x1d, 0x7c, 0x05, 0x30, 0x45, 0xba, 0xb8, 0xc2, 0xc5, 0x0c, 0x25,
	0x39, 0x83, 0xea, 0x30, 0xb1, 0x3a, 0xa7, 0x51, 0x75, 0x98, 0xec, 0xd3, 0x30, 0x87, 0x3e, 0x65,
	0x3a, 0x45, 0x57, 0xbe, 0x39, 0x61, 0xfd, 0xd1, 0xb9, 0xea, 0xd6, 0x1f, 0xd7, 0xac, 0x3f, 0x3a,
	0x57, 0x41, 0xcf, 0x94, 0x3a, 0xd7, 0x34, 0xd6, 0x46, 0xe9, 0x62, 0x41, 0x59, 0xea, 0xf6, 0x93,
	0x13, 0xe4, 0x31, 0x74, 0xc6, 0xaf, 0x05, 0xc7, 0x97, 0x99, 0xf1, 0xee, 0xbc, 0x94, 0xa1, 0xe0,
	0xef, 0x15, 0xe8, 0x4c, 0x44, 0xcc, 0x68, 0x7a, 0x85, 0x09, 0xa3, 0xa6, 0x7b, 0x7e, 0x8f, 0x33,
	0xc5, 0xb4, 0x8f, 0xcc, 0x93, 0xe4, 0x01, 0xb4, 0x2f, 0x69, 0x8c, 0x33, 0x21, 0x6e, 0x9c, 0xa1,
	0x35, 0x6d, 0xb4, 0xa6, 0x6f, 0x98, 0xd6, 0x28, 0x7d, 0xcf, 0x39, 0xd2, 0x68, 0xbd, 0x60, 0xfc,
	0x06, 0x93, 0x21, 0x77, 0xa5, 0xbd, 0xa6, 0xcd, 0xa9, 0x98, 0xb6, 0xa2, 0x73, 0x49, 0x17, 0xae,
	0xc2, 0x0b, 0xc0, 0xd8, 0x7c, 0x25, 0x32, 0x9d, 0xcd, 0x7c, 0x6d, 0x7b, 0x32, 0xf8, 0x5b, 0x15,
	0x5a, 0x97, 0x19, 0x4f, 0x18, 0x9f, 0x9b, 0xd2, 0x99, 0x0a, 0x4d, 0x53, 0x47, 0xdb, 0x4d, 0x37,
	0xa2, 0x0d, 0xcc, 0x64, 0xe1, 0x05, 0xd5, 0xa8, 0x74, 0x24, 0x32, 0xee, 0x7b, 0xb4, 0x0c, 0x91,
	0xa7, 0xf0, 0x5e, 0x89, 0x1c, 0x98, 0x99, 0x92, 0xc7, 0xb1, 0x0d, 0x93, 0x10, 0x48, 0x09, 0xf2,
	0x5e, 0xeb, 0xd6, 0xeb, 0x1e, 0x0e, 0xf9, 0xb1, 0x89, 0xf1, 0x16, 0x95, 0x16, 0x52, 0x75, 0x1b,
	0xb6, 0xa4, 0x3a, 0x61, 0x51, 0x10, 0x51, 0xc1, 0xcd, 0xbb, 0x20, 0x27, 0x6c, 0x65, 0x35, 0x7d,
	0x17, 0x14, 0x98, 0xd9, 0x68, 0x4e, 0x2f, 0x90, 0xeb, 0x89, 0xa6, 0x73, 0xec, 0xb6, 0xf2, 0x8d,
	0x6e, 0xc1, 0xc1, 0x10, 0x5a, 0x03, 0xd4, 0x94, 0xa5, 0xca, 0xe6, 0x79, 0x3c, 0x32, 0xd3, 0x31,
	0x53, 0xbe, 0x4d, 0xd7, 0x80, 0xc9, 0x4e, 0x5f, 0x2c, 0x96, 0x94, 0xaf, 0x4a, 0x8d, 0x5a, 0x86,
	0x82, 0x3f, 0x01, 0x5c, 0x7c, 0xbd, 0x44, 0xc9, 0x90, 0xc7, 0x58, 0x92, 0x2f, 0xb5, 0x5c, 0x19,
	0xb2, 0xdd, 0xa6, 0xa9, 0xd4, 0x83, 0x62, 0x36, 0x17, 0x80, 0x39, 0xd7, 0x8b, 0x8d, 0x1c, 0x7b,
	0xb2, 0x28, 0xfc, 0x7a, 0xa9, 0xf0, 0x83, 0xdf, 0x02, 0x14, 0xb1, 0x1d, 0xe1, 0xfd, 0x41, 0x69,
	0xc4, 0xb9, 0x3a, 0xf5, 0x74, 0xf0, 0xaf, 0xaa, 0xcf, 0x9f, 0x90, 0x3e, 0x3b, 0xdf, 0x83, 0xa6,
	0x39, 0x8f, 0xe1, 0xc0, 0xb5, 0xa5, 0xa3, 0xc8, 0xe7, 0x70, 0xd2, 0x97, 0x68, 0x86, 0x73, 0x4f,
	0x5b, 0x43, 0x9d, 0xf3, 0x07, 0x61, 0x7e, 0x63, 0x85, 0xfe, 0xc6, 0x0a, 0xa7, 0xfe, 0xc6, 0x8a,
	0x0a, 0x61, 0xa3, 0xf9, 0xbb, 0x65, 0xe2, 0x34, 0x6b, 0x87, 0x35, 0xd7, 0xc2, 0x3b, 0x25, 0x50,
	0x3f, 0xae, 0x04, 0x1a, 0x7b, 0x4b, 0x80, 0x7c, 0x04, 0xa7, 0x79, 0x97, 0x8f, 0xae, 0x2f, 0xbe,
	0x66, 0x5a, 0xd9, 0x8a, 0x6a, 0x44, 0x9b, 0xa0, 0xb9, 0xc9, 0x3c, 0xc0, 0xd6, 0x06, 0x94, 0x2d,
	0xab, 0x46, 0xb4, 0x8f, 0x55, 0xb6, 0x6b, 0xca, 0x5c, 0x75, 0xdb, 0x9b, 0x76, 0x2d, 0x18, 0xfc,
	0xbb, 0x02, 0x67, 0xf6, 0xd4, 0xb3, 0xe5, 0x37, 0x33, 0xd5, 0xad, 0x72, 0xf7, 0x76, 0xce, 0xdb,
	0xa1, 0xa3, 0xa3, 0xf5, 0x70, 0xf9, 0x14, 0xce, 0x5c, 0x65, 0xb9, 0x08, 0x6c, 0xa6, 0x8d, 0xa8,
	0xa3, 0xa3, 0x2d, 0x7e, 0xf0, 0xe7, 0x0a, 0xb4, 0x27, 0xa8, 0x35, 0xe3, 0x73, 0x45, 0x3e, 0x83,
	0xd3, 0x97, 0x42, 0xb3, 0x6b, 0x96, 0xbf, 0x38, 0xf2, 0xde, 0xeb, 0x9c, 0x9f, 0x86, 0x65, 0x34,
	0xda, 0x94, 0x31, 0xfb, 0x1a, 0x4b, 0x76, 0x4b, 0xe3, 0x95, 0xcb, 0x44, 0x3b, 0x74, 0x74, 0xe4,
	0x19, 0xe4, 0x43, 0x68, 0x8d, 0xe9, 0xca, 0x1c, 0x86, 0x8b, 0xf9, 0x24, 0x74, 0xb4, 0x8a, 0x3c,
	0x27, 0xe0, 0xd0, 0xf6, 0x20, 0xf9, 0x01, 0x34, 0x06, 0x38, 0x63, 0xda, 0xed, 0xa0, 0x11, 0xf6,
	0xa9, 0x4c, 0xa2, 0x1c, 0x23, 0x1f, 0x40, 0xb3, 0x2f, 0x31, 0x61, 0x3e, 0xf5, 0x8e, 0xeb, 0x40,
	0xf2, 0x04, 0x3a, 0x13, 0x8c, 0x33, 0xc9, 0xf4, 0x6a, 0xcc, 0xb8, 0x73, 0x58, 0x0f, 0xc7, 0x8c,
	0x47, 0x65, 0x46, 0xf0, 0xcf, 0x0a, 0xd4, 0x8d, 0x22, 0x79, 0x04, 0x60, 0x7e, 0xdd, 0x9d, 0x93,
	0x77, 0x68, 0x09, 0x31, 0x45, 0xee, 0xf5, 0xfa, 0x22, 0xf1, 0x13, 0x62, 0x03, 0xb3, 0x6d, 0x4e,
	0x65, 0xf2, 0x15, 0x5b, 0x5a, 0x91, 0x9a, 0x6b, 0xf3, 0x02, 0xb2, 0xd7, 0x51, 0x96, 0xa6, 0x76,
	0x0a, 0xb8, 0x8b, 0xc5, 0xd3, 0x66, 0xc4, 0xb8, 0x77, 0xa3, 0x6b, 0x8d, 0x9d, 0x67, 0x64, 0x73,
	0xdf, 0x33, 0xb2, 0xb5, 0xf5, 0x8c, 0xf4, 0xde, 0xdb, 0xb9, 0x0d, 0x47, 0x06, 0x3f, 0x87, 0xda,
	0x98, 0x71, 0x13, 0xe6, 0x98, 0xf1, 0x0b, 0x4e, 0x67, 0x29, 0xe6, 0x57, 0x7a, 0x3b, 0x2a, 0x21,
	0xe4, 0xbe, 0x15, 0x73, 0xd1, 0x99, 0xa5, 0xb9, 0x6b, 0xd7, 0x47, 0xf8, 0x04, 0xce, 0x7a, 0xb1,
	0x66, 0xb7, 0x4c, 0xaf, 0x4a, 0x83, 0xb9, 0x1d, 0x6d, 0xa1, 0x46, 0xce, 0xaa, 0x68, 0xec, 0xc5,
	0xb1, 0x79, 0xc7, 0xba, 0xe7, 0xcb, 0x16, 0x6a, 0xde, 0x84, 0xcf, 0x53, 0x11, 0xdf, 0x60, 0xe2,
	0x90, 0x61, 0xa2, 0xba, 0x35, 0xfb, 0x56, 0xd8, 0x65, 0x98, 0x19, 0x72, 0x95, 0xe9, 0x0d, 0xd9,
	0xfc, 0x5d, 0xb1, 0x0d, 0x07, 0xff, 0xad, 0xc2, 0xbd, 0x72, 0x81, 0x9a, 0xbc, 0x8f, 0x69, 0xa6,
	0xb0, 0x97, 0xa6, 0x6e, 0xcb, 0x6b, 0x9a, 0x4c, 0xe1, 0xfe, 0x58, 0x28, 0xad, 0x7a, 0x3c, 0xe9,
	0x8b, 0x45, 0x3e, 0x47, 0xf2, 0x9a, 0x7a, 0x1a, 0x1a, 0x46, 0x09, 0x1f, 0x67, 0xea, 0x75, 0xd9,
	0xae, 0x6f, 0x9a, 0x68, 0xc7, 0x02, 0x49, 0xe0, 0xbb, 0x97, 0x22, 0x4d, 0xc5, 0x1b, 0xc6, 0xe7,
	0x3d, 0x9e, 0xe4, 0x6b, 0x94, 0xca, 0x95, 0x62, 0x18, 0xee, 0xe5, 0xde, 0xe9, 0x60, 0xbf, 0x31,
	0x32, 0x82, 0xb3, 0x01, 0x93, 0x18, 0xeb, 0x2b, 0x54, 0x8a, 0xce, 0x51, 0xb9, 0xb1, 0xf0, 0x71,
	0xb8, 0x09, 0xdf, 0x69, 0x77, 0x4b, 0x9d, 0x5c, 0x42, 0xc7, 0x3e, 0xc2, 0x7a, 0x3c, 0x99, 0x2c,
	0xfc, 0xe4, 0xf8, 0x28, 0x2c, 0x61, 0x77, 0x9a, 0x2a, 0x2b, 0x06, 0x6f, 0x6b, 0xf0, 0xf1, 0x91,
	0xc9, 0x23, 0x3f, 0x83, 0xc6, 0x0b, 0x76, 0x83, 0x7e, 0xd2, 0x3c, 0x0a, 0xa7, 0x0c, 0x25, 0x26,
	0x77, 0xc8, 0x47, 0xb9, 0x30, 0x99, 0xc1, 0x43, 0xbb, 0x28, 0x79, 0x18, 0x71, 0x7b, 0x0c, 0xa3,
	0xeb, 0x57, 0x22, 0x73, 0x47, 0x78, 0xc8, 0xd8, 0x3b, 0x6d, 0x90, 0x2f, 0x00, 0x4a, 0x16, 0x6b,
	0x47, 0x59, 0x2c, 0x69, 0x90, 0x5f, 0x40, 0x7b, 0x5d, 0x52, 0xf5, 0xa3, 0xb4, 0xd7, 0xf2, 0xe4,
	0x39, 0xdc, 0x73, 0xeb, 0x3c, 0x39, 0x8d, 0xa3, 0xf4, 0x37, 0x74, 0x82, 0xbf, 0x54, 0xe1, 0xa7,
	0xff, 0x57, 0x9d, 0x91, 0x01, 0xdc, 0xf7, 0x42, 0x11, 0xfe, 0x31, 0x33, 0x9f, 0x5f, 0xee, 0x58,
	0xba, 0xe1, 0x5d, 0x3e, 0x77, 0x34, 0xc8, 0x14, 0xba, 0xbd, 0x38, 0xc6, 0xa5, 0xc6, 0x64, 0xc7,
	0x5a, 0xf5, 0x80, 0xb5, 0x3b, 0x35, 0xc9, 0x00, 0x4e, 0xaf, 0x90, 0xdb, 0x0b, 0x67, 0xc8, 0x9f,
	0x33, 0x71, 0xe4, 0x81, 0x6c, 0x2a, 0x05, 0xff, 0xa8, 0xc0, 0x93, 0xe3, 0x9a, 0x83, 0x3c, 0x87,
	0xf7, 0x9c, 0xcc, 0xd1, 0xb9, 0xd8, 0x56, 0x20, 0xe7, 0xd0, 0x72, 0xd0, 0xc1, 0xc8, 0xbd, 0x20,
	0xf9, 0x02, 0x4e, 0xbf, 0x94, 0x22, 0x5b, 0xae, 0xbd, 0xd6, 0x0e, 0x68, 0x6e, 0x8a, 0x07, 0x7f,
	0xad, 0xc2, 0x87, 0x47, 0x74, 0xac, 0xf1, 0x73, 0x89, 0x98, 0xcc, 0x68, 0x7c, 0x53, 0x7c, 0x86,
	0xbd, 0xd3, 0xcf, 0x86, 0x38, 0xf9, 0x35, 0x9c, 0x45, 0xb8, 0x60, 0x3c, 0x41, 0x69, 0x81, 0xc3,
	0x87, 0xbb, 0x25, 0x6f, 0x76, 0x30, 0x96, 0x22, 0xc9, 0x62, 0xed, 0x0c, 0x1c, 0x8c, 0x74, 0x43,
	0x9c, 0x7c, 0x0e, 0xf0, 0x12, 0xdf, 0x28, 0xa7, 0x5c, 0x3f, 0xa0, 0x5c, 0x92, 0x0d, 0xde, 0x56,
	0xe0, 0x83, 0x77, 0xd6, 0x8d, 0xb9, 0x0a, 0x47, 0xd7, 0xd7, 0xee, 0xba, 0x30, 0x4b, 0x73, 0x5d,
	0x5d, 0x4a, 0xb1, 0x18, 0xa3, 0x58, 0xa6, 0x38, 0xcc, 0xeb, 0xd3, 0xdd, 0x6c, 0xbb, 0x0c, 0xf3,
	0x62, 0x30, 0xe0, 0xc5, 0x2d, 0xca, 0x95, 0xe0, 0xe8, 0xfe, 0x3d, 0xd9, 0xc0, 0x82, 0x5f, 0xc2,
	0xf7, 0x8f, 0x77, 0x7f, 0x06, 0xd5, 0x11, 0x77, 0xfe, 0xaa, 0x23, 0x3e, 0x6b, 0xda, 0xb7, 0xe2,
	0x67, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x33, 0xb4, 0x53, 0x88, 0xad, 0x12, 0x00, 0x00,
}
