// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/startup-user/startupuser.proto

package startupuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	common "proto/common"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartupUser struct {
	UserID               uint32               `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Experience           []*common.Experience `protobuf:"bytes,5,rep,name=Experience,proto3" json:"Experience,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StartupUser) Reset()         { *m = StartupUser{} }
func (m *StartupUser) String() string { return proto.CompactTextString(m) }
func (*StartupUser) ProtoMessage()    {}
func (*StartupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f4c8930989ae083, []int{0}
}

func (m *StartupUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupUser.Unmarshal(m, b)
}
func (m *StartupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupUser.Marshal(b, m, deterministic)
}
func (m *StartupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupUser.Merge(m, src)
}
func (m *StartupUser) XXX_Size() int {
	return xxx_messageInfo_StartupUser.Size(m)
}
func (m *StartupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupUser.DiscardUnknown(m)
}

var xxx_messageInfo_StartupUser proto.InternalMessageInfo

func (m *StartupUser) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *StartupUser) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *StartupUser) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *StartupUser) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StartupUser) GetExperience() []*common.Experience {
	if m != nil {
		return m.Experience
	}
	return nil
}

func init() {
	proto.RegisterType((*StartupUser)(nil), "StartupUser")
}

func init() {
	proto.RegisterFile("proto/startup-user/startupuser.proto", fileDescriptor_1f4c8930989ae083)
}

var fileDescriptor_1f4c8930989ae083 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x49, 0x2c, 0x2a, 0x29, 0x2d, 0xd0, 0x2d, 0x2d, 0x4e, 0x2d, 0x82, 0x71,
	0x40, 0x6c, 0x3d, 0xb0, 0xb4, 0x94, 0x24, 0x44, 0x55, 0x72, 0x7e, 0x6e, 0x6e, 0x7e, 0x1e, 0x94,
	0x82, 0x4a, 0xc9, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x79, 0x49, 0xa5, 0x69, 0xfa,
	0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x10, 0x05, 0x4a, 0x77, 0x18, 0xb9, 0xb8,
	0x83, 0x21, 0x26, 0x86, 0x16, 0xa7, 0x16, 0x09, 0x89, 0x71, 0xb1, 0x81, 0x68, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x28, 0x4f, 0xc8, 0x82, 0x8b, 0xd3, 0xb9, 0x28, 0x35, 0xb1,
	0x24, 0x35, 0xc5, 0xb1, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0x62, 0xb8,
	0x1e, 0xcc, 0x70, 0xbd, 0x10, 0x98, 0xe1, 0x41, 0x08, 0xc5, 0x20, 0x9d, 0xa1, 0x05, 0x29, 0x50,
	0x9d, 0xcc, 0x84, 0x75, 0xc2, 0x15, 0x0b, 0x89, 0x70, 0xb1, 0x86, 0x64, 0x96, 0xe4, 0xa4, 0x4a,
	0xb0, 0x28, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0xda, 0x5c, 0x5c, 0xae, 0x15, 0x05, 0xa9,
	0x45, 0x99, 0xa9, 0x79, 0xc9, 0xa9, 0x12, 0xac, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xdc, 0x7a, 0x08,
	0xa1, 0x20, 0x24, 0xe9, 0x24, 0x36, 0xb0, 0x0d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3,
	0xb8, 0xc9, 0x8d, 0x49, 0x01, 0x00, 0x00,
}
